import { expect, test } from "@playwright/test";
import { createOperationalAssessment, createOperationalReferral, scheduleOperationalAssessment } from "./support/operational-api";

for (const width of [1440, 390]) test(`assessment preparation and appointment drafts resume without booking at ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 900 });
  const referral = await createOperationalReferral(page.request, "assessmentCoordinator", { name: "Synthetic Resumption", owner: "", tags: [] });
  const assessment = await createOperationalAssessment(page.request, referral.id);
  const workspace = `/?view=referrals&screen=packet&referralId=${referral.id}`;
  const read = async () => (await (await page.request.get(`/api/assessments/${assessment.assessment_id}`)).json()).assessment;
  const writes: string[] = [];
  page.on("request", request => { if (request.method() === "POST" && /\/(start|schedule)$/.test(new URL(request.url()).pathname)) writes.push(request.url()); });
  await page.goto(`${workspace}&workspaceStage=assessment`);
  await expect(page.getByRole("button", { name: "Prepare assessment", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Schedule interview", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Schedule interview", exact: true });
  await dialog.getByLabel("Assessment date and time", { exact: true }).fill("2026-10-12T10:30");
  await dialog.getByLabel("Assessment method", { exact: true }).selectOption("phone");
  await dialog.getByLabel("Phone number to call", { exact: true }).fill("555-0100");
  await dialog.getByRole("heading", { name: "Schedule interview", exact: true }).click();
  await expect(dialog.getByRole("status")).toContainText("draft saved");
  await expect(page).toHaveURL(/assessmentDialog=schedule/);
  await page.reload();
  await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel("Phone number to call", { exact: true })).toHaveValue("555-0100");
  await expect(dialog.getByLabel("Assessment date and time", { exact: true })).toHaveValue("2026-10-12T10:30");
  await expect(dialog.getByRole("status")).toContainText("not booked");
  await page.screenshot({ path: info.outputPath(`schedule-draft-${width}.png`) });
  expect((await read()).scheduled_start_at).toBeFalsy();
  expect((await read()).started_at).toBeFalsy();
  expect(writes).toEqual([]);
  await dialog.getByRole("button", { name: "Back to assessment", exact: true }).click();
  await expect(page).not.toHaveURL(/assessmentDialog/);
  await page.reload();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Prepare assessment", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Interview", exact: true }).click();
  await expect(page).toHaveURL(/assessmentMode=interview/);
  await page.reload();
  await expect(page).toHaveURL(/assessmentMode=interview/);
  if (width >= 768) await expect(page.getByRole("button", { name: "Interview", exact: true })).toHaveAttribute("aria-pressed", "true");
  else await expect(page.locator("[data-phone-interview]")).toBeVisible();
  expect((await read()).started_at).toBeFalsy();
  expect((await read()).assessment_date).toBeFalsy();
  await page.getByRole("button", { name: "Schedule interview", exact: true }).click();
  await expect(dialog.getByLabel("Phone number to call", { exact: true })).toHaveValue("555-0100");
  await dialog.getByRole("button", { name: "Schedule interview", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect((await read()).scheduled_start_at).toBeTruthy();
  expect((await read()).started_at).toBeFalsy();
  expect(writes.filter(url => url.endsWith("/schedule"))).toHaveLength(1);
  await page.reload();
  await expect(dialog).toHaveCount(0);
  await expect(page).toHaveURL(/assessmentMode=interview/);
  if (width >= 768) await expect(page.getByRole("button", { name: "Interview", exact: true })).toHaveAttribute("aria-pressed", "true");
  else await expect(page.locator("[data-phone-interview]")).toBeVisible();
});

test("opening from Workspaces resumes scheduling; a newer booking supersedes the old draft", async ({ page }) => {
  const referral = await createOperationalReferral(page.request, "assessmentCoordinator", { name: "Continuity Example", owner: "", tags: [] });
  const assessment = await createOperationalAssessment(page.request, referral.id);
  await page.goto(`/?view=referrals&screen=packet&referralId=${referral.id}&workspaceStage=assessment`);
  await page.getByRole("button", { name: "Schedule interview", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Schedule interview", exact: true });
  await dialog.getByLabel("Assessment date and time", { exact: true }).fill("2026-10-12T10:30");
  await dialog.getByLabel("Assessment address", { exact: true }).fill("Unbooked draft address");
  await dialog.getByRole("heading").click();
  await expect(dialog.getByRole("status")).toContainText("draft saved");
  await expect.poll(async () => {
    const response = await page.request.get("/api/me/work-continuity");
    return (await response.json()).state?.lastWorkspace?.location?.assessmentDialog;
  }).toBe("schedule");
  await page.goto("/?view=referrals");
  await page.getByRole("button", { name: "Open Continuity Example referral workspace", exact: true }).click();
  await expect(dialog).toBeVisible();
  await expect(dialog.getByLabel("Assessment address", { exact: true })).toHaveValue("Unbooked draft address");
  const scheduled = await scheduleOperationalAssessment(page.request, assessment);
  await page.reload();
  await expect(dialog.getByLabel("Zoom meeting link", { exact: true })).toHaveValue("Synthetic Zoom room");
  await expect(dialog.getByRole("status")).toContainText("appointment changed");
  const current = (await (await page.request.get(`/api/assessments/${assessment.assessment_id}`)).json()).assessment;
  expect(current.version).toBe(scheduled.version);
  expect(current.scheduled_location).toBe("Synthetic Zoom room");
});

test("a phone interview returns to the exact question and uses the prepared answers", async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 900 });
  const referral = await createOperationalReferral(page.request, "assessmentCoordinator", { name: "Synthetic Interview", owner: "", tags: [] });
  const assessment = await createOperationalAssessment(page.request, referral.id);
  await page.goto(`/?view=referrals&screen=packet&referralId=${referral.id}&workspaceStage=assessment&assessmentMode=prepare&assessmentSection=identity&assessmentQuestion=referrer_contact`);
  const pocket = page.locator("[data-phone-interview]");
  const input = page.getByRole("textbox", { name: "Referrer contact", exact: true });
  await input.fill("Synthetic contact");
  await page.getByRole("button", { name: "Interview", exact: true }).click();
  const read = async () => (await (await page.request.get(`/api/assessments/${assessment.assessment_id}`)).json()).assessment;
  await expect.poll(async () => (await read()).referrer_contact).toBe("Synthetic contact");
  await pocket.getByRole("button", { name: "Choose questionnaire section", exact: true }).click();
  const sections = page.getByRole("dialog", { name: "Questionnaire sections", exact: true });
  await sections.getByRole("button", { name: /2\. How things are now/ }).click();
  const firstField = await pocket.locator("[data-working-field]").getAttribute("data-working-field");
  await pocket.getByRole("button", { name: "Next", exact: true }).click();
  const resumedField = await pocket.locator("[data-working-field]").getAttribute("data-working-field");
  expect(resumedField).toBeTruthy();
  expect(resumedField).not.toBe(firstField);
  await expect(page).toHaveURL(new RegExp(`assessmentQuestion=${resumedField}(?:&|$)`));
  await page.reload();
  await expect(pocket.locator("[data-working-field]")).toHaveAttribute("data-working-field", resumedField!);
  expect((await read()).started_at).toBeFalsy();
  expect((await read()).assessment_date).toBeFalsy();
  await page.screenshot({ path: info.outputPath("interview-resume-phone.png") });
});

test("Workspaces resumes scheduling while the Board opens preparation without booking", async ({ page }) => {
  const referral = await createOperationalReferral(page.request, "assessmentCoordinator", { name: "Synthetic Return", owner: "", tags: [] });
  const assessment = await createOperationalAssessment(page.request, referral.id);
  await page.goto("/?view=referrals");
  await page.getByRole("button", { name: "Open Synthetic Return referral workspace", exact: true }).click();
  await page.getByRole("navigation", { name: "Workspace stages", exact: true }).getByRole("button", { name: "Assessment", exact: true }).click();
  await page.getByRole("button", { name: "Schedule interview", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Schedule interview", exact: true });
  await expect(dialog).toBeVisible();
  await page.goBack();
  await page.getByRole("button", { name: "Open Synthetic Return referral workspace", exact: true }).click();
  await expect(dialog).toBeVisible();
  await page.goto("/");
  await page.getByRole("button", { name: "Open Synthetic Return", exact: true }).locator("[data-folder-name]").click();
  await expect(page).toHaveURL(/workspaceStage=assessment/);
  await expect(page).not.toHaveURL(/workspaceEntry=resume|assessmentDialog=/);
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Prepare assessment", exact: true })).toHaveAttribute("aria-pressed", "true");
  // Choosing the Board's next action does not discard the saved appointment draft.
  await page.getByRole("button", { name: "Schedule interview", exact: true }).click();
  await expect(dialog).toBeVisible();
  const current = (await (await page.request.get(`/api/assessments/${assessment.assessment_id}`)).json()).assessment;
  expect(current.scheduled_start_at).toBeFalsy();
  expect(current.started_at).toBeFalsy();
});

test("Workspaces resumes Begin interview; Keep preparing and Board navigation never start it", async ({ page }) => {
  const referral = await createOperationalReferral(page.request, "assessmentCoordinator", { name: "Synthetic Confirmation", owner: "", tags: [] });
  const assessment = await createOperationalAssessment(page.request, referral.id);
  await page.goto(`/?view=referrals&screen=packet&referralId=${referral.id}&workspaceStage=assessment`);
  await page.getByRole("button", { name: "Begin interview", exact: true }).click();
  const begin = page.getByRole("dialog", { name: "Begin interview", exact: true });
  await expect(begin).toBeVisible();
  await page.goto("/?view=referrals");
  await page.getByRole("button", { name: "Open Synthetic Confirmation referral workspace", exact: true }).click();
  await expect(begin).toBeVisible();
  const read = async () => (await (await page.request.get(`/api/assessments/${assessment.assessment_id}`)).json()).assessment;
  expect((await read()).started_at).toBeFalsy();
  await begin.getByRole("button", { name: "Keep preparing", exact: true }).click();
  await page.goto("/?view=referrals");
  await page.getByRole("button", { name: "Open Synthetic Confirmation referral workspace", exact: true }).click();
  await expect(begin).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Prepare assessment", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Begin interview", exact: true }).click();
  await expect(begin).toBeVisible();
  await page.goto("/");
  await page.getByRole("button", { name: "Open Synthetic Confirmation", exact: true }).locator("[data-folder-name]").click();
  await expect(begin).toHaveCount(0);
  await expect(page).not.toHaveURL(/workspaceEntry=resume|assessmentDialog=/);
  await expect(page.getByRole("button", { name: "Prepare assessment", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect((await read()).started_at).toBeFalsy();
});
