import {test, expect} from '@playwright/test';
import {createCanvas} from '@napi-rs/canvas';
import {randomUUID} from 'node:crypto';
import {createOperationalReferral} from './support/operational-api';
import {confirmReferralFileLabels} from './support/referral-upload';

test('partial batch keeps successful files and retries only remaining files without duplicates', async ({page})=>{
  const referral=await createOperationalReferral(page.request,'assessmentCoordinator',{name:`Synthetic Retry ${randomUUID()}`,owner:'Annette Everhart',documentName:'',documentStatus:'Missing'},{assigneeId:'provisional:allo:annette'});
  const listFiles=async()=>(await(await page.request.get(`/api/files?referral_id=${referral.id}`)).json()).files;
  await page.goto(`/?view=referrals&screen=packet&referralId=${referral.id}&workspaceView=files`);
  await page.route('**/api/uploads/create-url',route=>route.request().postData()?.includes('second-note.txt')?route.fulfill({status:503,json:{error:'Synthetic upload interruption'}}):route.continue());
  await page.getByLabel('Choose referral documents').setInputFiles([
    {name:'first-note.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic first file')},
    {name:'second-note.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic second file')},
  ]);
  await confirmReferralFileLabels(page);
  await expect(page.getByRole('button',{name:'Retry saving',exact:true})).toBeEnabled();
  expect((await listFiles()).map((f:any)=>f.name)).toEqual(['first-note.txt']);
  await expect(page.getByRole('list',{name:'Queued referral files'})).toContainText('second-note.txt');
  await page.unroute('**/api/uploads/create-url');
  await page.getByRole('button',{name:'Retry saving',exact:true}).click();
  await expect.poll(async()=>(await listFiles()).map((f:any)=>f.name).sort()).toEqual(['first-note.txt','second-note.txt']);
  await expect(page.getByRole('list',{name:'Queued referral files'})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('region',{name:'Uploaded documents',exact:true}).getByRole('listitem')).toHaveCount(2);
});

test('Files page browser audit: previews, repeated upload, X, confirmation, failure, mobile', async ({page}, info) => {
  test.setTimeout(120000);
  const referral = await createOperationalReferral(page.request, 'assessmentCoordinator', {name: `Synthetic Files Audit ${randomUUID()}`, owner:'Annette Everhart', documentName:'', documentStatus:'Missing', phone:'555-0101'}, {assigneeId:'provisional:allo:annette'});
  const listFiles = async () => (await (await page.request.get(`/api/files?referral_id=${referral.id}`)).json()).files;
  await page.goto(`/?view=referrals&screen=packet&referralId=${referral.id}&workspaceView=files`);
  const canvas = createCanvas(400, 500); const ctx = canvas.getContext('2d');
  ctx.fillStyle = 'white'; ctx.fillRect(0,0,400,500); ctx.fillStyle = '#173c2b'; ctx.font='20px sans-serif'; ctx.fillText('SYNTHETIC DOCUMENT',30,50);
  const packet = {name:'synthetic-assessment-note.png', mimeType:'image/png', buffer:canvas.toBuffer('image/png')};
  const upload = async () => { await page.getByLabel('Choose referral documents').setInputFiles(packet); await confirmReferralFileLabels(page, {[packet.name]:'assessment'}); };
  await page.screenshot({path:info.outputPath('files-empty.png')});
  await upload();
  await expect.poll(async()=> (await listFiles()).length).toBe(1);
  const list=page.getByRole('region',{name:'Uploaded documents',exact:true});
  await expect(list.getByText('Uploaded',{exact:true})).toBeVisible();
  await upload();
  await expect(page.getByTestId('workspace-save-status')).toContainText('Files uploaded');
  expect(await listFiles()).toHaveLength(1);
  await page.screenshot({path:info.outputPath('files-desktop.png')});
  await list.getByRole('button',{name:`Preview ${packet.name}`,exact:true}).click();
  const preview=page.getByRole('dialog',{name:`Preview ${packet.name}`,exact:true});
  await expect(preview.locator('iframe')).toBeVisible();
  console.log('PREVIEW_FOCUS_ON_OPEN',await page.evaluate(()=>({label:document.activeElement?.getAttribute('aria-label'),inside:!!document.activeElement?.closest('[role="dialog"]')})));
  await page.keyboard.press('Tab');
  console.log('PREVIEW_FOCUS_AFTER_TAB',await page.evaluate(()=>({label:document.activeElement?.getAttribute('aria-label'),text:document.activeElement?.textContent?.slice(0,80),inside:!!document.activeElement?.closest('[role="dialog"]')})));
  await page.screenshot({path:info.outputPath('files-preview.png')});
  await preview.getByRole('button',{name:'Close preview',exact:true}).click();
  await list.getByRole('button',{name:`Delete ${packet.name}`}).click();
  const dialog=page.getByRole('dialog',{name:'Delete this file?',exact:true});
  await expect(dialog).toBeVisible();
  await page.screenshot({path:info.outputPath('files-delete-confirm.png')});
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
  expect(await listFiles()).toHaveLength(1);
  await list.getByRole('button',{name:`Delete ${packet.name}`}).click();
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  expect(await listFiles()).toHaveLength(1);
  const file=(await listFiles())[0];
  await page.route(`**/api/files/${file.id}`,async route=>route.request().method()==='DELETE'?route.fulfill({status:500,json:{error:'Synthetic delete failure'}}):route.continue());
  await list.getByRole('button',{name:`Delete ${packet.name}`}).click();
  await dialog.getByRole('button',{name:'Delete file',exact:true}).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  expect(await listFiles()).toHaveLength(1);
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
  await page.unroute(`**/api/files/${file.id}`);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:info.outputPath('files-phone.png')});
  console.log('PHONE_OVERFLOW',await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth})));
  await list.getByRole('button',{name:`Delete ${packet.name}`}).click();
  await page.screenshot({path:info.outputPath('files-delete-phone.png')});
  await dialog.getByRole('button',{name:'Delete file',exact:true}).click();
  await expect.poll(async()=> (await listFiles()).length).toBe(0);
  await expect(list).toHaveCount(0);
  await page.getByText('Document checklist',{exact:true}).click();
  console.log('CHECKLIST_AFTER_DELETE',await page.getByRole('region',{name:'Document checklist',exact:true}).innerText());
  const activity=(await (await page.request.get(`/api/referrals/${referral.id}/activity`)).json()).events;
  console.log('DOCUMENT_AUDIT_ACTIONS',activity.filter((e:any)=>e.action.startsWith('document_')).map((e:any)=>e.action));
  const latest=(await (await page.request.get(`/api/referrals/${referral.id}`)).json()).referral;
  expect(latest.phone).toBe('555-0101');
  await upload();
  await expect.poll(async()=> (await listFiles()).length).toBe(1);
  await expect(page.getByTestId('workspace-save-status')).toContainText('Files uploaded');
  await page.route('**/api/files?**', route=>route.fulfill({status:503,json:{error:'Synthetic inventory unavailable'}}));
  const failedInventory=page.waitForResponse(response=>response.url().includes('/api/files?') && response.status()===503);
  await page.reload();
  await failedInventory;
  await expect(page.getByTestId('packet-workspace')).toHaveAttribute('aria-busy','false');
  await expect(page.getByRole('button',{name:/Drop files or choose files/})).toBeEnabled();
  await expect(page.getByLabel('Choose referral documents')).toBeAttached();
  await expect(page.getByRole('region',{name:'Uploaded documents',exact:true})).toHaveCount(0);
  console.log('FAILED_INVENTORY_VISIBLE_ALERTS',await page.getByRole('alert').allTextContents());
  await page.screenshot({path:info.outputPath('files-inventory-failure.png')});
});
