import type { AcademyJourney } from "@/lib/academy/academy-types";

export const academyJourneys: readonly AcademyJourney[] = [
  {
    id: "referral-intake",
    title: "Inbound referral to durable workspace",
    trigger: "A county referral reaches the admissions coordinator.",
    outcome: "One authorized, audited referral workspace exists with an honest packet state.",
    failureQuestion: "What remains true if PostgreSQL commits but packet upload fails?",
    moduleIds: ["admissions-operating-model", "create-referral", "route-handler-contract", "stores-transactions"],
    steps: [
      { label: "Construct the referral command", owner: "ReferralPacketCanvas", runtime: "Browser", source: "components/pipeline/ReferralPacketCanvas.tsx", invariant: "Only deliberate client-owned fields enter the request." },
      { label: "Establish request trust", owner: "POST /api/referrals", runtime: "Next.js", source: "app/api/referrals/route.ts", invariant: "Identity, origin, size, shape, role, and assignment are checked." },
      { label: "Commit relational truth", owner: "ReferralStore", runtime: "PostgreSQL", source: "lib/pipeline/referral-store.ts", invariant: "Referral, person, audit, work, version, and idempotency commit together." },
      { label: "Upload immutable packet", owner: "Upload reservation", runtime: "Blob", source: "lib/pipeline/referral-packet-upload.ts", invariant: "Reservation, bytes, hash, and completion are distinct durable facts." },
      { label: "Reconcile partial outcomes", owner: "Upload reconciler", runtime: "Worker", source: "lib/extraction/durable-upload-reconciliation.ts", invariant: "Retry never invents upload success or duplicates the referral." },
    ],
  },
  {
    id: "packet-extraction",
    title: "Packet upload to reviewed structured evidence",
    trigger: "A completed, malware-cleared packet is ready for processing.",
    outcome: "Reviewable field candidates retain page-level provenance and accepted values have durable human decisions.",
    failureQuestion: "Which attempt may commit when an expired worker reports after its replacement?",
    moduleIds: ["upload-storage", "extraction-worker", "provenance-review", "quality-backlog-recovery"],
    steps: [
      { label: "Create page manifest", owner: "Document processing", runtime: "Worker", source: "lib/extraction/document-processing.ts", invariant: "Pages are ordered and normalized without changing raw source bytes." },
      { label: "Claim an extraction attempt", owner: "Processing worker", runtime: "PostgreSQL", source: "lib/extraction/processing-worker.ts", invariant: "A bounded lease identifies the current attempt." },
      { label: "Extract structured candidates", owner: "Extraction service", runtime: "External", source: "lib/extraction/extraction-service.ts", invariant: "Provider output remains untrusted and schema constrained." },
      { label: "Validate and persist evidence", owner: "Worker report boundary", runtime: "Next.js", source: "app/api/internal/extraction/report/route.ts", invariant: "Late attempts cannot overwrite current processing state." },
      { label: "Review each field", owner: "Packet reviewer", runtime: "Browser", source: "components/pipeline/PacketExtractionReview.tsx", invariant: "Acceptance records actor, source, confidence, and evidence." },
    ],
  },
  {
    id: "pre-assessment",
    title: "Referral evidence to assessment readiness",
    trigger: "Packet extraction and admission-document review are underway.",
    outcome: "Assessment readiness is determined from reviewed, durable evidence without fabricating missing information.",
    failureQuestion: "Does a high-confidence medication candidate satisfy assessor ownership?",
    moduleIds: ["pre-assessment-workflow", "assessment-schema-ownership", "workflow-state"],
    steps: [
      { label: "Reconcile required documents", owner: "Requirement reconciler", runtime: "Next.js", source: "lib/pipeline/document-requirement-reconciliation.ts", invariant: "Present, missing, rejected, and not-applicable remain distinct." },
      { label: "Review packet fields", owner: "Admissions coordinator", runtime: "Browser", source: "components/pipeline/PacketExtractionReview.tsx", invariant: "Conflicts and nulls remain visible." },
      { label: "Compute transition blockers", owner: "Referral workflow", runtime: "Next.js", source: "lib/pipeline/referral-workflow.ts", invariant: "Readiness follows one deterministic server policy." },
      { label: "Seed the assessment", owner: "Assessment seed", runtime: "Next.js", source: "lib/assessment/assessment-seed.ts", invariant: "Referral evidence is distinguishable from assessor findings." },
    ],
  },
  {
    id: "assessment-lifecycle",
    title: "Assessment schedule to immutable signature",
    trigger: "A ready referral is assigned to an assessor.",
    outcome: "The assessment has accurate timing, attribution, structured answers, signature, and append-only corrections.",
    failureQuestion: "What happens when a stale editor saves after signature?",
    moduleIds: ["assessment-schema-ownership", "assessment-lifecycle", "concurrency-idempotency"],
    steps: [
      { label: "Schedule the assessment", owner: "Schedule command", runtime: "Next.js", source: "app/api/assessments/[assessmentId]/schedule/route.ts", invariant: "Zoom or other method and appointment do not start performance time." },
      { label: "Start performance", owner: "Start command", runtime: "Next.js", source: "app/api/assessments/[assessmentId]/start/route.ts", invariant: "The explicit command starts timing and preserves assessor of record." },
      { label: "Edit versioned sections", owner: "Assessment workspace", runtime: "Browser", source: "components/pipeline/AssessmentWorkspace.tsx", invariant: "Disjoint edits may proceed; stale same-section edits conflict." },
      { label: "Sign immutable history", owner: "Signature command", runtime: "PostgreSQL", source: "lib/assessment/assessment-store.ts", invariant: "Signed content cannot be rewritten." },
      { label: "Append a correction", owner: "Addendum command", runtime: "Next.js", source: "app/api/assessments/[assessmentId]/addenda/route.ts", invariant: "Original, correction, reason, actor, and time remain visible." },
    ],
  },
  {
    id: "decision-handoff",
    title: "Recommendation to admission decision and EHR handoff",
    trigger: "A signed assessment is ready for supervisory review.",
    outcome: "One authorized terminal decision exists and accepted records reach downstream creation idempotently.",
    failureQuestion: "Can a late recommendation or worker event overwrite the terminal decision?",
    moduleIds: ["assessment-decision-handoff", "medication-decision-ehr", "workflow-state"],
    steps: [
      { label: "Record assessment recommendation", owner: "Recommendation route", runtime: "Next.js", source: "app/api/referrals/[referralId]/recommendation/route.ts", invariant: "Recommendation remains separate from final authority." },
      { label: "Commit final decision", owner: "Decision route", runtime: "PostgreSQL", source: "app/api/referrals/[referralId]/decision/route.ts", invariant: "Role, evidence, actor, and expected version guard the terminal write." },
      { label: "Build reviewed handoff payload", owner: "Client update contracts", runtime: "Next.js", source: "lib/integration/client-update-contracts.ts", invariant: "Only required accepted facts enter the payload." },
      { label: "Queue and publish idempotently", owner: "Client update outbox", runtime: "PostgreSQL", source: "lib/integration/client-update-outbox.ts", invariant: "Retry cannot create a duplicate downstream client." },
    ],
  },
  {
    id: "collaborative-edit",
    title: "Concurrent referral editing without lost updates",
    trigger: "Multiple operators and a worker act on the same referral.",
    outcome: "Disjoint work is preserved, conflicts are explicit, and human terminal truth is protected.",
    failureQuestion: "How does the UI recover after a same-section version conflict?",
    moduleIds: ["referral-workspace-ui", "concurrency-idempotency", "frontend-resilience"],
    steps: [
      { label: "Acquire editing presence", owner: "Presence route", runtime: "Next.js", source: "app/api/referrals/[referralId]/presence/route.ts", invariant: "Presence is advisory and lease bounded." },
      { label: "Submit expected section version", owner: "Referral workspace", runtime: "Browser", source: "components/pipeline/ReferralPacketCanvas.tsx", invariant: "The command identifies the version the operator actually saw." },
      { label: "Compare and commit", owner: "ReferralStore", runtime: "PostgreSQL", source: "lib/pipeline/referral-store.ts", invariant: "Stale same-section writes fail; current disjoint writes may commit." },
      { label: "Reconcile the draft", owner: "Draft recovery", runtime: "Browser", source: "lib/pipeline/referral-draft-recovery.ts", invariant: "Newer truth is reread before another write." },
    ],
  },
  {
    id: "canonical-profile",
    title: "Referral identity to canonical client profile",
    trigger: "Referral, clinical census, history, and assessment records may describe the same person.",
    outcome: "A reviewed canonical identity joins records without silent merge or split.",
    failureQuestion: "What happens when two canonical residents are plausible?",
    moduleIds: ["identity-matching-reconciliation", "clinical-adapter-profiles"],
    steps: [
      { label: "Generate candidate evidence", owner: "Master matcher", runtime: "Next.js", source: "lib/pipeline/master-record-matching.ts", invariant: "Candidate generation does not create a canonical link." },
      { label: "Review resident link", owner: "Resident link store", runtime: "PostgreSQL", source: "lib/pipeline/resident-link-store.ts", invariant: "Ambiguity and DOB conflicts require explicit review." },
      { label: "Resolve canonical assessment identity", owner: "Assessment identity resolver", runtime: "Next.js", source: "lib/assessment/assessment-client-identity.ts", invariant: "Only confirmed links authorize canonical joins." },
      { label: "Project unified profile", owner: "Unified profile", runtime: "Next.js", source: "lib/pipeline/unified-profile.ts", invariant: "The client receives a minimal authorized DTO." },
    ],
  },
  {
    id: "operational-report",
    title: "Operational question to trustworthy report",
    trigger: "An operator or leader asks for queue, timing, census, source, or export information.",
    outcome: "The answer has deterministic scope, grain, evidence rows, freshness, and safe export behavior.",
    failureQuestion: "Which layer chooses time period, community, and row grain?",
    moduleIds: ["read-models-search-operations", "query-performance-retention"],
    steps: [
      { label: "Parse bounded scope", owner: "Query contract", runtime: "Next.js", source: "lib/pipeline/referral-query.ts", invariant: "Scope and filters are explicit, validated, and deterministic." },
      { label: "Execute indexed projection", owner: "Read store", runtime: "PostgreSQL", source: "lib/pipeline/referral-store.ts", invariant: "Row grain and ordering are stable and bounded." },
      { label: "Compose operational meaning", owner: "Operations snapshot", runtime: "Next.js", source: "lib/pipeline/operations-snapshot.ts", invariant: "Counts and exceptions derive from canonical facts." },
      { label: "Render preview or export", owner: "Operations UI", runtime: "Browser", source: "components/pipeline/OperationsDashboard.tsx", invariant: "Preview limits do not silently truncate full export truth." },
    ],
  },
  {
    id: "release",
    title: "Commit to reversible production release",
    trigger: "An approved change is ready to ship.",
    outcome: "The exact artifact, schema, configuration, tests, smoke evidence, and recovery path are known.",
    failureQuestion: "What evidence distinguishes repository readiness from live environment health?",
    moduleIds: ["test-assurance", "operations-recovery-release", "vertical-change-capstone"],
    steps: [
      { label: "Classify change impact", owner: "CI impact", runtime: "Tooling", source: "scripts/ci-change-impact.mjs", invariant: "Affected risk surfaces select the required controls." },
      { label: "Run deterministic and live gates", owner: "Readiness registry", runtime: "Tooling", source: "scripts/platform-readiness.mjs", invariant: "Static presence is not confused with live certification." },
      { label: "Protect schema compatibility", owner: "Migration runner", runtime: "PostgreSQL", source: "scripts/apply-database-migrations.mjs", invariant: "Applied migrations remain immutable and ordered." },
      { label: "Create immutable evidence", owner: "Release evidence", runtime: "Tooling", source: "scripts/create-release-evidence.mjs", invariant: "Artifact identity and checksums bind evidence to the release." },
      { label: "Deploy, smoke, and recover", owner: "Production runbook", runtime: "External", source: "docs/PRODUCTION_DEPLOYMENT_RUNBOOK.md", invariant: "Rollback or forward-fix criteria are explicit before deployment." },
    ],
  },
  {
    id: "incident-recovery",
    title: "Signal to verified service recovery",
    trigger: "Latency, queue age, inconsistency, dependency failure, or error rate crosses an owned threshold.",
    outcome: "Impact is contained, truth is reconciled, service is verified, and the failure becomes a permanent test.",
    failureQuestion: "Which recovery actions are safe to retry and what proves completion?",
    moduleIds: ["operations-recovery-release", "quality-backlog-recovery", "query-performance-retention"],
    steps: [
      { label: "Detect bounded service signal", owner: "Pipeline metrics", runtime: "Next.js", source: "lib/observability/pipeline-metrics.ts", invariant: "Metrics remain low-cardinality and PHI-free." },
      { label: "Triage owned alert", owner: "Azure alert", runtime: "External", source: "infra/azure/operational-alerts.bicep", invariant: "Every alert maps to severity, owner, and runbook." },
      { label: "Contain and reconcile", owner: "Recovery command", runtime: "Worker", source: "scripts/chaos-recovery-replay.mjs", invariant: "Recovery is bounded and idempotent." },
      { label: "Verify data and service", owner: "Operational certification", runtime: "Tooling", source: "scripts/operational-certification.mjs", invariant: "HTTP health alone does not prove data consistency." },
      { label: "Create permanent replay", owner: "Regression suite", runtime: "Tooling", source: "scripts/critical-safety-contracts.mjs", invariant: "The real failure can no longer pass silently." },
    ],
  },
] as const;
