import type {
  AcademyActivity,
  AcademyCompetency,
  AcademyModule,
  AcademyModuleDefinition,
  AcademyTrack,
} from "@/lib/academy/academy-types";

export const ACADEMY_CURRICULUM_VERSION = "2026.08.enterprise.1";

export const academyTracks: readonly AcademyTrack[] = [
  {
    id: "foundations",
    number: 1,
    title: "Engineering foundations",
    shortTitle: "Foundations",
    summary: "Build the language, runtime, database, debugging, and repository-navigation skills needed to reason from source instead of guessing.",
    outcome: "You can run the system, identify a runtime boundary, read an unfamiliar module, and prove what the code does.",
  },
  {
    id: "product",
    number: 2,
    title: "Admissions product and workflow",
    shortTitle: "Product",
    summary: "Learn the behavioral-health admissions operating model and every durable transition from referral receipt to EHR handoff.",
    outcome: "You can explain the product to an operator and trace each clinical and operational handoff to its owner.",
  },
  {
    id: "frontend",
    number: 3,
    title: "Frontend architecture",
    shortTitle: "Frontend",
    summary: "Understand the Pipeline shell, complex referral and assessment workspaces, responsive behavior, drafts, errors, and accessibility.",
    outcome: "You can safely change a user journey without moving business truth into browser state.",
  },
  {
    id: "api-domain",
    number: 4,
    title: "API and domain policy",
    shortTitle: "API + domain",
    summary: "Trace route handlers through authentication, validation, authorization, domain policy, persistence, and bounded errors.",
    outcome: "You can add or review a server command without bypassing policy or exposing untrusted data.",
  },
  {
    id: "data",
    number: 5,
    title: "PostgreSQL and data integrity",
    shortTitle: "Data",
    summary: "Own the schema, migrations, adapters, transactions, concurrency controls, identity matching, query plans, and recovery model.",
    outcome: "You can make a safe data change, explain its invariants, and recover it when something fails.",
  },
  {
    id: "documents-ai",
    number: 6,
    title: "Documents, extraction, and AI",
    shortTitle: "Documents + AI",
    summary: "Follow immutable packet bytes through Blob storage, normalization, extraction, provenance, human review, quality measurement, and replay.",
    outcome: "You can distinguish source evidence, machine proposals, reviewed facts, and clinical decisions under partial failure.",
  },
  {
    id: "clinical",
    number: 7,
    title: "Clinical and assessment systems",
    shortTitle: "Clinical",
    summary: "Learn canonical client identity, clinical integration, assessment field ownership, lifecycle commands, medications, decisions, and EHR handoff.",
    outcome: "You can preserve clinical history and ownership across referral, assessment, and downstream systems.",
  },
  {
    id: "security",
    number: 8,
    title: "Identity, authorization, and privacy",
    shortTitle: "Security",
    summary: "Understand Entra authentication, sessions, role and assignment authorization, PHI boundaries, abuse controls, and supply-chain policy.",
    outcome: "You can identify and defend every trust boundary without relying on UI visibility as a control.",
  },
  {
    id: "reliability",
    number: 9,
    title: "Assurance and production operations",
    shortTitle: "Reliability",
    summary: "Use deterministic tests, browser journeys, database certification, observability, capacity, chaos, release evidence, backup, and restore.",
    outcome: "You can decide whether a release is safe and lead recovery with evidence rather than intuition.",
  },
  {
    id: "ownership",
    number: 10,
    title: "System ownership practicum",
    shortTitle: "Ownership",
    summary: "Integrate every discipline in a bounded production-style change and defend the design, tests, migration, rollout, and rollback.",
    outcome: "You can own a vertical slice from product intent through production recovery and teach it to another engineer.",
  },
] as const;

const definitions: readonly AcademyModuleDefinition[] = [
  {
    id: "system-map",
    trackId: "foundations",
    number: 1,
    level: "foundation",
    title: "Repository map and runtime boundaries",
    summary: "Orient yourself in the monorepo and separate browser, Next.js, PostgreSQL, Blob, worker, and external-system responsibilities.",
    minutes: 120,
    prerequisites: [],
    objectives: ["Navigate every top-level source area", "Name the durable owner of a fact", "Trace one request across runtime zones"],
    concepts: ["File-system routing and shared layouts", "Server versus client module graphs", "Durable state ownership and trust transitions"],
    sources: [
      { path: "docs/ARCHITECTURE.md", purpose: "Canonical architecture narrative" },
      { path: "app/(pipeline)/layout.tsx", purpose: "Pipeline route composition" },
      { path: "components/pipeline/PipelineAppShell.tsx", purpose: "Cross-page browser shell" },
      { path: "docs/FILE_MAP.md", purpose: "Curated subsystem map" },
    ],
    trace: ["Start at app/(pipeline)/page.tsx and identify every imported boundary", "Mark each module as browser, server, database, worker, or documentation", "For five displayed values, name the system that owns the durable truth"],
    lab: {
      title: "Draw the production runtime map",
      scenario: "An operator reports that a packet appears in the browser but disappears after refresh.",
      instructions: ["Draw all runtime zones and arrows", "Annotate validation, authorization, persistence, and retry at every arrow", "Identify the first durable success state and two honest partial-failure states"],
      evidencePrompt: "Record your runtime map, the durable owner at each boundary, and your diagnosis of the disappearing packet.",
      acceptanceCriteria: ["All six runtime zones appear", "Browser state is not described as durable", "At least two recovery paths are explicit"],
    },
    check: {
      prompt: "A referral name exists in React state. What has been proven?",
      options: ["The referral is durable", "Only the current browser has a draft value", "The server authorized the value"],
      answer: 1,
      explanation: "React state is a browser draft. Durable truth starts only after an authorized server command commits.",
    },
  },
  {
    id: "types-and-boundaries",
    trackId: "foundations",
    number: 2,
    level: "foundation",
    title: "TypeScript, contracts, and runtime validation",
    summary: "Use TypeScript for internal guarantees while keeping network, database, file, and worker values unknown until validated.",
    minutes: 150,
    prerequisites: ["system-map"],
    objectives: ["Read unions and narrowing", "Distinguish a type from a validator", "Protect server-owned fields"],
    concepts: ["Structural typing and discriminated unions", "Unknown input at trust boundaries", "Domain ownership versus form ownership"],
    sources: [
      { path: "lib/pipeline/referral-types.ts", purpose: "Referral domain types" },
      { path: "lib/pipeline/referral-validation.ts", purpose: "Runtime create and patch validation" },
      { path: "lib/extraction/contracts.ts", purpose: "Bounded API payload parsing" },
      { path: "lib/extraction/worker-report-validation.ts", purpose: "Untrusted worker callback validation" },
    ],
    trace: ["Follow unknown JSON into a discriminated validation result", "List fields the browser may propose and fields the server must derive", "Find three unsafe outcomes prevented by request-size or value bounds"],
    lab: {
      title: "Review an unsafe request cast",
      scenario: "A change casts request.json() directly to a referral command and forwards it to the store.",
      instructions: ["List every missing runtime guarantee", "Design a discriminated validation result", "Write negative cases for shape, ownership, bounds, and unknown keys"],
      evidencePrompt: "Explain why the cast is unsafe and provide the validator contract and negative-test matrix you would require.",
      acceptanceCriteria: ["Compile-time and runtime guarantees are separated", "Server-owned fields are identified", "Failures are bounded and actionable"],
    },
    check: {
      prompt: "What does `body as ReferralCreateInput` do at runtime?",
      options: ["Validates every field", "Changes compiler belief only", "Removes unknown fields"],
      answer: 1,
      explanation: "A type assertion emits no runtime validation and cannot enforce field ownership or bounds.",
    },
  },
  {
    id: "next-react-runtime",
    trackId: "foundations",
    number: 3,
    level: "foundation",
    title: "React 19 and Next.js 16 execution model",
    summary: "Understand App Router pages, layouts, route handlers, Server and Client Components, hydration, navigation, and error boundaries as this repository uses them.",
    minutes: 150,
    prerequisites: ["types-and-boundaries"],
    objectives: ["Choose the correct component runtime", "Explain hydration and navigation", "Read a route handler without Pages Router assumptions"],
    concepts: ["Server Components by default", "Client module graph boundaries", "Layouts, route groups, loading, and error UI"],
    sources: [
      { path: "app/layout.tsx", purpose: "Root document and providers" },
      { path: "app/(pipeline)/layout.tsx", purpose: "Nested application layout" },
      { path: "app/(pipeline)/error.tsx", purpose: "Route error recovery" },
      { path: "app/api/referrals/route.ts", purpose: "Next.js 16 Route Handler" },
      { path: "next.config.ts", purpose: "Framework and deployment behavior" },
    ],
    trace: ["Classify each imported module under a client boundary", "Explain initial HTML, RSC payload, hydration, and later navigation", "Identify what persists across nested route navigation and what remounts"],
    lab: {
      title: "Place a feature in the correct runtime",
      scenario: "A new training panel needs database metadata, an interactive filter, and no secret leakage.",
      instructions: ["Split server data preparation from client interaction", "Define the minimal serializable DTO", "Explain where authorization and caching belong"],
      evidencePrompt: "Provide the proposed component tree and justify every server/client boundary and serialized prop.",
      acceptanceCriteria: ["Secrets never enter client props", "Interactive code is isolated", "Authorization occurs before data projection"],
    },
    check: {
      prompt: "What happens to imports below a `use client` boundary?",
      options: ["They may enter the client module graph", "They always stay server-only", "Next.js ignores them"],
      answer: 0,
      explanation: "A client directive defines a client module-graph boundary, so imported code must be browser-safe.",
    },
  },
  {
    id: "developer-toolchain",
    trackId: "foundations",
    number: 4,
    level: "foundation",
    title: "Local development, Git, debugging, and commands",
    summary: "Operate the repository safely: install deterministically, run the app, inspect failures, use worktrees, classify commands, and avoid destructive shortcuts.",
    minutes: 150,
    prerequisites: ["next-react-runtime"],
    objectives: ["Run and diagnose the local stack", "Choose the correct readiness command", "Make reversible Git changes"],
    concepts: ["Lockfile-based installs and environment contracts", "Focused checks versus certification bundles", "Logs, browser console, network, and server traces"],
    sources: [
      { path: "package.json", purpose: "Canonical command surface" },
      { path: "README.md", purpose: "Local setup entry point" },
      { path: ".env.example", purpose: "Configuration contract" },
      { path: "docs/refactoring/WORKTREE_RUNBOOK.md", purpose: "Isolated change workflow" },
      { path: "scripts/platform-readiness.mjs", purpose: "Fast release-feedback orchestration" },
    ],
    trace: ["Classify package scripts as static, deterministic, browser, database, live, or destructive", "Follow one failed command to its owning script and exit condition", "Explain how a dirty worktree changes safe debugging and rollback choices"],
    lab: {
      title: "Build a failure-first debugging runbook",
      scenario: "The UI loads, a save returns 500, and the browser displays a generic recovery message.",
      instructions: ["Order the browser, network, server, domain, and database checks", "Name the evidence captured at each step", "Define a stop condition before changing code"],
      evidencePrompt: "Write the exact debugging sequence, commands, evidence, and decision points you would use.",
      acceptanceCriteria: ["Diagnosis precedes code edits", "The smallest truthful test runs first", "No destructive Git or data command is used"],
      commands: ["npm run dev", "npm run check:platform:fast", "npm run build"],
    },
    check: {
      prompt: "What should happen before changing code for an unexplained 500?",
      options: ["Delete build output and retry blindly", "Capture the failing boundary and smallest reproduction", "Reset the worktree"],
      answer: 1,
      explanation: "A bounded reproduction and evidence identify the owner and prevent speculative edits.",
    },
  },
  {
    id: "database-foundations",
    trackId: "foundations",
    number: 5,
    level: "foundation",
    title: "SQL, PostgreSQL, and transactional thinking",
    summary: "Learn relational keys, constraints, indexes, transactions, isolation, locks, query plans, and the PostgreSQL client patterns used by Pipeline.",
    minutes: 180,
    prerequisites: ["developer-toolchain"],
    objectives: ["Read schema and query code", "Define an atomic business command", "Explain index and lock purpose"],
    concepts: ["Constraints as executable invariants", "Transactions and rollback", "Optimistic versions, advisory locks, and row locks"],
    sources: [
      { path: "database/migrations/0001_pipeline_core.sql", purpose: "Core relational schema" },
      { path: "lib/database/pipeline-database.ts", purpose: "Bounded PostgreSQL connection" },
      { path: "lib/pipeline/referral-store.ts", purpose: "Transactional store implementation" },
      { path: "scripts/postgres-query-plan-fixtures.mjs", purpose: "Planner assertions" },
    ],
    trace: ["Map primary, foreign, unique, and check constraints in the core migration", "Find one transaction and list facts that commit together", "Explain the race closed by one application lock and one unique index"],
    lab: {
      title: "Review a relational command",
      scenario: "Referral creation must write a person, referral, audit event, work item, and idempotency result exactly once.",
      instructions: ["Choose the transaction boundary", "Identify unique and foreign-key defenses", "Describe retry behavior before, during, and after commit"],
      evidencePrompt: "Document the atomic unit, constraints, locks, idempotency behavior, and failure outcomes.",
      acceptanceCriteria: ["All relational facts commit together", "External Blob work is outside the transaction", "Retry behavior is deterministic"],
    },
    check: {
      prompt: "Why keep a unique database constraint when application code checks duplicates first?",
      options: ["To close concurrent races", "Only to improve CSS rendering", "To replace validation"],
      answer: 0,
      explanation: "The database constraint remains the final race-resistant authority under concurrency.",
    },
  },
  {
    id: "admissions-operating-model",
    trackId: "product",
    number: 6,
    level: "practitioner",
    title: "Behavioral-health admissions operating model",
    summary: "Translate the real coordinator workflow into product stages, evidence requirements, roles, organizational views, and measurable outcomes.",
    minutes: 150,
    prerequisites: ["database-foundations"],
    objectives: ["Explain the email-to-decision flow", "Separate community, month, and workflow axes", "Name stage owners and evidence"],
    concepts: ["Referral as the durable workspace", "Community and received month as organization", "Workflow stages as guarded clinical operations"],
    sources: [
      { path: "docs/PIPELINE_V1_SPEC.md", purpose: "Product intent" },
      { path: "docs/REFERRAL_OPERATING_RELIABILITY_PLAN.md", purpose: "Operating model and reliability" },
      { path: "lib/reliability/referral-operating-model.ts", purpose: "Deterministic operating envelopes" },
      { path: "lib/pipeline/community-config.ts", purpose: "Canonical communities" },
      { path: "lib/pipeline/workspace-presentation.ts", purpose: "Month and community presentation" },
    ],
    trace: ["Map inbound referral, pre-assessment, assessment, post-assessment, decision, and handoff", "For every stage identify actor, required evidence, blocker, and next action", "Separate navigation organization from clinical workflow state"],
    lab: {
      title: "Run an operator tabletop",
      scenario: "A county packet arrives, medication pages are missing, an assessment is scheduled, and a supervisor must decide.",
      instructions: ["Place every action in the correct stage", "Identify who may act and what blocks advancement", "Describe what each role sees next"],
      evidencePrompt: "Write the complete operator timeline with role, evidence, blocker, and durable stage after each action.",
      acceptanceCriteria: ["No stage is skipped", "Missing medication evidence remains visible", "Recommendation and final decision stay separate"],
    },
    check: {
      prompt: "What should community and received month primarily control?",
      options: ["Navigation and organization", "Clinical authorization", "Whether evidence is valid"],
      answer: 0,
      explanation: "Community and month organize workspaces; workflow policy and authorization control clinical actions.",
    },
  },
  {
    id: "create-referral",
    trackId: "product",
    number: 7,
    level: "practitioner",
    title: "Create a referral end to end",
    summary: "Trace one complete vertical slice from the browser form through validation, assignment, transaction, direct packet upload, audit, and recovery.",
    minutes: 180,
    prerequisites: ["admissions-operating-model"],
    objectives: ["Trace the create call path", "Explain packet deduplication", "Model PostgreSQL and Blob partial failure"],
    concepts: ["Deliberate command construction", "Transactional relational truth", "Direct upload and distributed reconciliation"],
    sources: [
      { path: "components/pipeline/ReferralPacketCanvas.tsx", purpose: "Referral draft and submit UI" },
      { path: "app/api/referrals/route.ts", purpose: "Create request boundary" },
      { path: "lib/pipeline/referral-validation.ts", purpose: "Create command validation" },
      { path: "lib/pipeline/referral-store.ts", purpose: "Local and PostgreSQL creation" },
      { path: "lib/pipeline/referral-packet-upload.ts", purpose: "Packet reservation and direct upload" },
    ],
    trace: ["Start at the submit event and write every called symbol in order", "Record trust, authorization, side effect, and failure at every step", "Explain retry after relational commit but before Blob completion"],
    lab: {
      title: "Produce the golden create-referral trace",
      scenario: "A coordinator submits the same packet twice after the first browser request times out.",
      instructions: ["Trace both attempts through all runtime zones", "Explain mutation idempotency and packet-hash dedupe", "Define the operator-visible recovery result"],
      evidencePrompt: "Provide the complete symbol trace and exact behavior of both attempts, including audit and upload state.",
      acceptanceCriteria: ["Every trust boundary is named", "The database remains race-resistant", "The second attempt cannot create a silent duplicate"],
      commands: ["npm run check:journeys", "npm run check:api"],
    },
    check: {
      prompt: "A Blob target was reserved but no completion sentinel exists. What is true?",
      options: ["The packet definitely uploaded", "Only the target reservation is durable", "Extraction is complete"],
      answer: 1,
      explanation: "Reservation does not prove that bytes arrived or passed completion checks.",
    },
  },
  {
    id: "pre-assessment-workflow",
    trackId: "product",
    number: 8,
    level: "practitioner",
    title: "Pre-assessment readiness and packet review",
    summary: "Understand document requirements, extracted fields, medication carry-forward, missing-information blockers, assignment, and scheduling readiness.",
    minutes: 180,
    prerequisites: ["create-referral"],
    objectives: ["Distinguish packet status from clinical readiness", "Trace reviewed medication evidence", "Explain assessment blockers"],
    concepts: ["Requirement evidence and not-applicable reasons", "Human-confirmed extraction", "Referral-owned context versus assessment-owned answers"],
    sources: [
      { path: "lib/pipeline/document-requirements.ts", purpose: "Canonical admission-document requirements" },
      { path: "lib/pipeline/document-requirement-reconciliation.ts", purpose: "Requirement evidence reconciliation" },
      { path: "components/pipeline/PacketExtractionReview.tsx", purpose: "Human field review" },
      { path: "lib/assessment/assessment-seed.ts", purpose: "Reviewed referral-to-assessment seed" },
      { path: "lib/pipeline/referral-progress.ts", purpose: "Workflow readiness projection" },
    ],
    trace: ["Follow one medication candidate from packet evidence into an assessment seed", "List every durable fact used to declare assessment readiness", "Identify which missing facts block and which remain warnings"],
    lab: {
      title: "Resolve a mixed-quality packet",
      scenario: "A packet has a face sheet, conflicting medication lists, no TB result, and an illegible conservatorship page.",
      instructions: ["Classify requirements and extraction candidates", "Choose review and retry actions without inventing values", "Determine whether assessment scheduling and start are allowed"],
      evidencePrompt: "Record the evidence state, review decisions, blockers, and safe next action for every document and medication field.",
      acceptanceCriteria: ["Conflicts preserve provenance", "Illegible data becomes null plus review", "Readiness follows durable rules rather than judgment in the UI"],
    },
    check: {
      prompt: "Can a high-confidence extracted medication become a signed assessment fact automatically?",
      options: ["Yes, confidence is authorization", "No, it remains reviewable evidence", "Only when the filename says medications"],
      answer: 1,
      explanation: "Extraction confidence measures a proposal; human review and assessment ownership determine accepted clinical facts.",
    },
  },
  {
    id: "assessment-decision-handoff",
    trackId: "product",
    number: 9,
    level: "practitioner",
    title: "Assessment, recommendation, decision, and EHR handoff",
    summary: "Follow assignment, Zoom scheduling, explicit start, structured completion, signature, recommendation, final decision, and accepted-record export.",
    minutes: 180,
    prerequisites: ["pre-assessment-workflow"],
    objectives: ["Separate scheduling from performance", "Protect signed history", "Explain accepted-only handoff"],
    concepts: ["Lifecycle commands and assessor of record", "Append-only signed evidence", "Recommendation versus authorized final decision"],
    sources: [
      { path: "components/pipeline/AssessmentWorkspace.tsx", purpose: "Assessment operator surface" },
      { path: "lib/assessment/assessment-lifecycle-validation.ts", purpose: "Lifecycle command rules" },
      { path: "lib/assessment/assessment-store.ts", purpose: "Assessment persistence and history" },
      { path: "app/api/referrals/[referralId]/decision/route.ts", purpose: "Final decision boundary" },
      { path: "app/api/referrals/[referralId]/ehr-handoff/route.ts", purpose: "Accepted-record handoff command" },
    ],
    trace: ["Trace schedule, start, save, sign, recommend, decide, and handoff as separate commands", "Identify actor, version, and audit evidence for each", "Explain correction after signature and failure after handoff queueing"],
    lab: {
      title: "Defend the final decision sequence",
      scenario: "An assessor signs, recommends acceptance, a supervisor decides, and a stale browser submits a conflicting decline.",
      instructions: ["Sequence every command and expected version", "Show why the stale command fails", "Explain the accepted-only EHR payload and retry path"],
      evidencePrompt: "Document the lifecycle timeline, authorization, immutable records, stale-write result, and handoff recovery.",
      acceptanceCriteria: ["Signature cannot be rewritten", "Recommendation does not become the decision", "A stale terminal write cannot win"],
    },
    check: {
      prompt: "What starts the assessment-duration clock?",
      options: ["Creating a draft", "Scheduling a Zoom meeting", "The explicit assessment start command"],
      answer: 2,
      explanation: "Draft preparation and scheduling are distinct from actual assessment performance.",
    },
  },
  {
    id: "shell-navigation",
    trackId: "frontend",
    number: 10,
    level: "practitioner",
    title: "Application shell, navigation, and responsive layout",
    summary: "Understand header actions, route selection, workspace navigation, month/community organization, context providers, and mobile adaptation.",
    minutes: 135,
    prerequisites: ["assessment-decision-handoff"],
    objectives: ["Trace shell state and navigation", "Preserve route semantics", "Evaluate responsive constraints"],
    concepts: ["Shared shell context", "URL and presentation state", "Stable navigation under narrow viewports"],
    sources: [
      { path: "components/pipeline/PipelineAppShell.tsx", purpose: "Application composition" },
      { path: "components/pipeline/PipelineHeader.tsx", purpose: "Header navigation and profile" },
      { path: "components/pipeline/PipelineActionNav.tsx", purpose: "Primary action navigation" },
      { path: "components/pipeline/pipeline-shell-context.tsx", purpose: "Cross-page UI context" },
      { path: "lib/pipeline/client-navigation.ts", purpose: "Typed client navigation targets" },
    ],
    trace: ["Follow a workspace selection from click to rendered page", "Identify shell state that may remain ephemeral", "Test layout decisions at desktop, tablet, and 390px widths"],
    lab: {
      title: "Review a navigation change",
      scenario: "A new report view must be reachable without adding another primary header button or breaking mobile navigation.",
      instructions: ["Choose the correct navigation level", "Define route and accessible name behavior", "List desktop and mobile checks"],
      evidencePrompt: "Provide the navigation placement, route/state behavior, accessibility contract, and responsive test matrix.",
      acceptanceCriteria: ["No duplicate entry point", "The URL remains meaningful", "Keyboard and mobile use are covered"],
    },
    check: {
      prompt: "Which state belongs in shell context?",
      options: ["A final admission decision", "Temporary cross-page presentation state", "The authoritative packet bytes"],
      answer: 1,
      explanation: "Shell context coordinates presentation; durable clinical and document truth belongs behind server boundaries.",
    },
  },
  {
    id: "referral-workspace-ui",
    trackId: "frontend",
    number: 11,
    level: "advanced",
    title: "Referral directory, worklist, and workspace UI",
    summary: "Read the large referral surfaces as composed workflows: directory queries, action-first worklists, packet canvas, progress, activity, and file preview.",
    minutes: 210,
    prerequisites: ["shell-navigation"],
    objectives: ["Decompose complex client components", "Keep one source of UI truth", "Connect operator actions to server commands"],
    concepts: ["Directory versus exception-first worklist", "Draft recovery and section editing", "Progress and activity as projections"],
    sources: [
      { path: "components/pipeline/ReferralHome.tsx", purpose: "Referral and file directory" },
      { path: "components/pipeline/ReferralWorklist.tsx", purpose: "Action-oriented referral queue" },
      { path: "components/pipeline/ReferralPacketCanvas.tsx", purpose: "Referral workspace and creation" },
      { path: "components/pipeline/ReferralProgressPanel.tsx", purpose: "Progress projection" },
      { path: "components/pipeline/ReferralActivityPanel.tsx", purpose: "Audit activity presentation" },
      { path: "components/pipeline/ReferralFilePreviewDialog.tsx", purpose: "Bounded document preview" },
    ],
    trace: ["Separate data loading, state, derived presentation, and mutations in each surface", "Find every fetch and name its API contract", "Identify duplicated or derived state that could become stale"],
    lab: {
      title: "Trace one operator session",
      scenario: "A coordinator finds an urgent referral, opens its packet, updates a section, reviews activity, and returns to the same filtered list.",
      instructions: ["Trace state and requests for the full session", "Identify refresh and conflict behavior", "Propose focused tests for lost filters, stale edits, and preview failure"],
      evidencePrompt: "Record the UI state machine, network calls, durable mutations, recovery behavior, and focused test cases.",
      acceptanceCriteria: ["List state and record state stay distinct", "Section conflicts are visible", "Preview failure does not corrupt referral state"],
    },
    check: {
      prompt: "Why should progress usually be derived from durable referral facts?",
      options: ["To avoid a second mutable truth", "To make the font larger", "To remove API authorization"],
      answer: 0,
      explanation: "Derived progress avoids divergence between a progress number and the evidence that actually determines readiness.",
    },
  },
  {
    id: "assessment-calendar-profiles-ui",
    trackId: "frontend",
    number: 12,
    level: "advanced",
    title: "Assessment, calendar, profiles, and operations UI",
    summary: "Understand the remaining major surfaces and how they project assessment history, schedules, client identity, census, work queues, and operational status.",
    minutes: 210,
    prerequisites: ["referral-workspace-ui"],
    objectives: ["Trace assessment editing", "Explain calendar event projection", "Read unified profile and operations surfaces"],
    concepts: ["Section-owned assessment drafts", "Calendar as a projection, not workflow truth", "Joined profiles and bounded operational read models"],
    sources: [
      { path: "components/pipeline/AssessmentWorkspace.tsx", purpose: "Assessment editor and lifecycle" },
      { path: "components/pipeline/PipelineCalendar.tsx", purpose: "Assessment and referral calendar" },
      { path: "components/pipeline/ClientProfileDirectory.tsx", purpose: "Client directory" },
      { path: "components/pipeline/ClientProfileView.tsx", purpose: "Unified client profile" },
      { path: "components/pipeline/OperationsDashboard.tsx", purpose: "Operational dashboard" },
      { path: "components/pipeline/PipelineOverviewRoute.tsx", purpose: "Home and command-center composition" },
    ],
    trace: ["Map each surface to its API and server projection", "Identify which screen can mutate and which is read-only", "Find empty, loading, error, conflict, and permission-denied states"],
    lab: {
      title: "Audit the cross-surface handoff",
      scenario: "An assessment is rescheduled, signed, and then appears in the profile and operational queues.",
      instructions: ["Trace each surface refresh", "Identify the authoritative record and derived projections", "Design tests for stale calendar and profile data"],
      evidencePrompt: "Explain the data flow across assessment, calendar, profile, and operations views, including invalidation and recovery.",
      acceptanceCriteria: ["Calendar is not treated as authoritative", "Signed history remains immutable", "Projection lag has an explicit recovery path"],
    },
    check: {
      prompt: "What should a calendar event represent in Pipeline?",
      options: ["A projection of durable scheduling facts", "The only assessment record", "An authorization grant"],
      answer: 0,
      explanation: "Calendar UI projects schedule facts; it does not replace the assessment lifecycle record or access policy.",
    },
  },
  {
    id: "frontend-resilience",
    trackId: "frontend",
    number: 13,
    level: "advanced",
    title: "Accessibility, drafts, offline behavior, and frontend performance",
    summary: "Build interfaces that remain usable under keyboard, narrow viewport, reload, conflict, slow network, dependency failure, and offline conditions.",
    minutes: 165,
    prerequisites: ["assessment-calendar-profiles-ui"],
    objectives: ["Use semantic interaction patterns", "Protect draft recovery", "Measure navigation and render behavior"],
    concepts: ["Accessible names, focus, and dialogs", "Recoverable drafts and explicit conflicts", "Performance budgets and offline boundaries"],
    sources: [
      { path: "app/(pipeline)/error.tsx", purpose: "Route recovery boundary" },
      { path: "app/(pipeline)/loading.tsx", purpose: "Route loading behavior" },
      { path: "lib/pipeline/referral-draft-recovery.ts", purpose: "Referral draft recovery policy" },
      { path: "lib/offline/offline-assessment-store.ts", purpose: "Bounded offline assessment state" },
      { path: "tests/e2e/responsive-accessibility.spec.ts", purpose: "Accessibility and viewport evidence" },
      { path: "tests/e2e/performance-navigation.spec.ts", purpose: "Navigation performance evidence" },
    ],
    trace: ["List focus and keyboard contracts for every modal and tab surface", "Trace a draft across reload, server conflict, and successful save", "Explain what the service worker may and may not cache"],
    lab: {
      title: "Design a failure-complete interaction",
      scenario: "A user edits an assessment on a poor connection while another user updates the same section.",
      instructions: ["Define saving, offline, conflict, and retry states", "Protect user input without overwriting newer truth", "Specify keyboard and screen-reader announcements"],
      evidencePrompt: "Provide the interaction state machine, accessible status messaging, and conflict recovery sequence.",
      acceptanceCriteria: ["No silent lost update", "Offline state is honest", "Focus and status behavior are explicit"],
    },
    check: {
      prompt: "What should happen after an optimistic-concurrency conflict?",
      options: ["Blindly retry the same payload", "Reload current truth and reconcile the draft", "Hide the error"],
      answer: 1,
      explanation: "A conflict means newer durable truth exists and must be compared before another write.",
    },
  },
  {
    id: "route-handler-contract",
    trackId: "api-domain",
    number: 14,
    level: "practitioner",
    title: "Route Handler anatomy and API contracts",
    summary: "Read the common request lifecycle: identity, origin, bounded parsing, validation, resource access, domain command, response mapping, metrics, and safe errors.",
    minutes: 150,
    prerequisites: ["frontend-resilience"],
    objectives: ["Trace Route Handlers consistently", "Map errors to bounded status codes", "Identify method and caching semantics"],
    concepts: ["Web Request and Response APIs", "No implicit caching for mutations", "Public error contracts and internal typed causes"],
    sources: [
      { path: "app/api/referrals/route.ts", purpose: "Collection read and create" },
      { path: "app/api/referrals/[referralId]/route.ts", purpose: "Resource read and patch" },
      { path: "app/api/assessments/[assessmentId]/route.ts", purpose: "Assessment resource boundary" },
      { path: "lib/observability/api-logging.ts", purpose: "Request logging wrapper" },
      { path: "scripts/api-route-policy-audit.mjs", purpose: "Exhaustive route policy inventory" },
    ],
    trace: ["Create a standard route-handler checklist from three routes", "Classify every expected failure and status", "Identify route-specific policy that must not be hidden in a generic helper"],
    lab: {
      title: "Specify a new mutation endpoint",
      scenario: "A referral needs a versioned, role-gated command to acknowledge a missing-information resolution.",
      instructions: ["Define method, path, body, and response", "Order all security and validation checks", "Map conflict, forbidden, invalid, missing, and unavailable outcomes"],
      evidencePrompt: "Write the endpoint contract and ordered boundary checklist without implementing it.",
      acceptanceCriteria: ["Same-origin and identity are distinct", "Resource authorization is explicit", "No raw exception or PHI enters the response"],
    },
    check: {
      prompt: "Are Route Handler GET responses cached by default in this Next.js version?",
      options: ["No", "Yes, always", "Only when TypeScript is disabled"],
      answer: 0,
      explanation: "Route Handlers are dynamic by default unless caching is deliberately enabled.",
    },
  },
  {
    id: "validation-authorization",
    trackId: "api-domain",
    number: 15,
    level: "advanced",
    title: "Validation, authentication, and resource authorization",
    summary: "Keep shape validation, caller identity, role capability, assignment, record state, and browser request protection as separate enforceable controls.",
    minutes: 180,
    prerequisites: ["route-handler-contract"],
    objectives: ["Build a negative authorization matrix", "Explain same-origin protection", "Enforce server-owned fields"],
    concepts: ["Authentication versus authorization", "Role plus resource plus state", "Defense in depth at mutations"],
    sources: [
      { path: "lib/auth/pipeline-auth.ts", purpose: "Identity and role model" },
      { path: "lib/auth/request-security.ts", purpose: "Same-origin mutation protection" },
      { path: "lib/pipeline/referral-access.ts", purpose: "Referral resource access" },
      { path: "lib/assessment/assessment-access.ts", purpose: "Assessment assignment policy" },
      { path: "scripts/security-boundary-check.mjs", purpose: "Security boundary static controls" },
    ],
    trace: ["Build a role-by-command matrix for referral and assessment routes", "Trace one assigned-assessor denial and supervisor override", "Explain why hiding a button proves nothing about server permission"],
    lab: {
      title: "Attack the authorization boundary",
      scenario: "A viewer crafts direct requests, an assessor targets another assessor's case, and a stale admin session attempts a terminal change.",
      instructions: ["Predict each response and audit outcome", "Identify the exact enforcing function", "Add missing negative cases to a test matrix"],
      evidencePrompt: "Provide the adversarial request matrix with expected status, enforcing source, and audit evidence.",
      acceptanceCriteria: ["Every denial is server-enforced", "Assignment and role are both tested", "Terminal state and version are considered"],
    },
    check: {
      prompt: "What does a valid request body prove about permission?",
      options: ["Nothing by itself", "The user is an admin", "The record is assigned"],
      answer: 0,
      explanation: "Shape validity and authorization are independent controls.",
    },
  },
  {
    id: "workflow-state",
    trackId: "api-domain",
    number: 16,
    level: "advanced",
    title: "Referral state machine and evidence guards",
    summary: "Own the legal transition graph, deterministic blockers, work-item evidence, terminal decisions, recovery actions, and workflow projections.",
    minutes: 180,
    prerequisites: ["validation-authorization"],
    objectives: ["Read and test the transition graph", "Explain every forward blocker", "Protect terminal outcomes"],
    concepts: ["Finite-state policy", "Evidence-backed invariants", "Projection versus command"],
    sources: [
      { path: "lib/pipeline/referral-workflow.ts", purpose: "Stage definitions and transition policy" },
      { path: "lib/pipeline/workflow-records.ts", purpose: "Workflow evidence contracts" },
      { path: "lib/pipeline/workflow-store.ts", purpose: "Durable transition and decision state" },
      { path: "app/api/referrals/[referralId]/transition/route.ts", purpose: "Guarded transition command" },
      { path: "app/api/referrals/[referralId]/work-items/route.ts", purpose: "Requirement evidence projection" },
    ],
    trace: ["Build the full allowed-transition table", "For each forward edge list durable blockers and recovery", "Explain how a late worker is prevented from reversing a human terminal decision"],
    lab: {
      title: "Model every workflow edge",
      scenario: "Product proposes a shortcut from new referral directly to assessment when a packet appears complete.",
      instructions: ["Compare the shortcut to current policy", "List bypassed evidence and actors", "Design the safe sequence and regression cases"],
      evidencePrompt: "Provide the current graph, rejected shortcut analysis, safe alternative, and tests for every affected edge.",
      acceptanceCriteria: ["Policy remains server-owned", "Blockers come from durable evidence", "Stage skipping is explicitly tested"],
    },
    check: {
      prompt: "Where must the final transition rule be enforced?",
      options: ["Only in drag and drop", "In server-enforced domain policy", "In CSS"],
      answer: 1,
      explanation: "Clients are not authoritative; the server command must enforce one shared state policy.",
    },
  },
  {
    id: "read-models-search-operations",
    trackId: "api-domain",
    number: 17,
    level: "advanced",
    title: "Queries, search, reports, and operational read models",
    summary: "Understand bounded filters, keyset pagination, facets, fuzzy search, operational snapshots, work queues, calendar projection, and reporting contracts.",
    minutes: 165,
    prerequisites: ["workflow-state"],
    objectives: ["Separate commands from projections", "Read pagination and filter contracts", "Explain dashboard freshness"],
    concepts: ["Bounded query parsing", "Deterministic read-model composition", "Aggregate operational truth without PHI leakage"],
    sources: [
      { path: "lib/pipeline/referral-query.ts", purpose: "Referral query parsing" },
      { path: "lib/pipeline/referral-sort-cursor.ts", purpose: "Stable keyset pagination" },
      { path: "lib/pipeline/site-search.ts", purpose: "Cross-surface search" },
      { path: "lib/pipeline/operations-snapshot.ts", purpose: "Operational projection" },
      { path: "app/api/operations/dashboard/route.ts", purpose: "Dashboard response boundary" },
      { path: "lib/pipeline/calendar-store.ts", purpose: "Calendar event projection" },
    ],
    trace: ["Follow filters from URL or UI to database query and response metadata", "Explain cursor stability when rows are inserted", "Identify freshness, row count, and scope metadata needed by a report"],
    lab: {
      title: "Design a trustworthy report",
      scenario: "Leadership asks for time-to-assessment by community and month with exact-row export.",
      instructions: ["Define scope, grain, filters, and authoritative timestamps", "Specify preview versus full export", "Include freshness, row count, and safe empty/error states"],
      evidencePrompt: "Write the report contract, query shape, metadata, and tests that prevent scope or grain errors.",
      acceptanceCriteria: ["The LLM is not choosing data grain", "Scope and freshness are explicit", "Large exports avoid rendering every row in chat or cards"],
    },
    check: {
      prompt: "Why prefer keyset pagination for large mutable referral lists?",
      options: ["It gives stable bounded traversal", "It disables indexes", "It stores rows in React"],
      answer: 0,
      explanation: "A stable sort tuple and cursor avoid deep offsets and reduce duplicate or skipped rows during change.",
    },
  },
  {
    id: "schema-migrations",
    trackId: "data",
    number: 18,
    level: "advanced",
    title: "Schema evolution and all migrations",
    summary: "Read the complete migration sequence, checksum policy, additive rollout rules, rollback drills, constraints, indexes, and compatibility responsibilities.",
    minutes: 210,
    prerequisites: ["read-models-search-operations"],
    objectives: ["Explain every migration's purpose", "Plan additive schema change", "Detect checksum drift"],
    concepts: ["Append-only applied migrations", "Expand-contract deployment", "Schema and application compatibility"],
    sources: [
      { path: "database/migrations/0001_pipeline_core.sql", purpose: "Core tables" },
      { path: "database/migrations/0004_document_processing.sql", purpose: "Document and extraction schema" },
      { path: "database/migrations/0007_canonical_client_assessments.sql", purpose: "Canonical client and assessment schema" },
      { path: "database/migrations/0015_assessor_workflow.sql", purpose: "Assessor lifecycle expansion" },
      { path: "database/migrations/0017_referral_received_month.sql", purpose: "Received-month organization" },
      { path: "database/migrations/0018_academy_progress.sql", purpose: "Private durable Academy progress state" },
      { path: "scripts/apply-database-migrations.mjs", purpose: "Ordered checksum-protected runner" },
      { path: "database/migration-checksums.json", purpose: "Migration integrity baseline" },
    ],
    trace: ["Create a table-by-table change log from migrations 0001 through 0018", "Identify every constraint alteration and why it remained compatible", "Explain plan, apply, verify, rollback-drill, and production rollout order"],
    lab: {
      title: "Plan an additive field migration",
      scenario: "A new optional referral source classification must be queryable and later required for selected sources.",
      instructions: ["Design expand, backfill, validation, and contract phases", "Choose constraints and index timing", "Define rollback or forward-fix behavior"],
      evidencePrompt: "Provide the migration sequence, compatibility matrix, query impact, verification, and rollback plan.",
      acceptanceCriteria: ["Old code remains compatible during expand", "Backfill is resumable", "Applied migration text is never edited"],
      commands: ["npm run database:migrate:plan", "npm run database:rollback:drill"],
    },
    check: {
      prompt: "What should happen when an applied migration checksum changes?",
      options: ["Ignore it", "Fail and require a new migration", "Rewrite production history"],
      answer: 1,
      explanation: "Applied migrations are immutable history; changes require an additive migration.",
    },
  },
  {
    id: "stores-transactions",
    trackId: "data",
    number: 19,
    level: "advanced",
    title: "Store adapters and transactional invariants",
    summary: "Understand local and PostgreSQL adapter parity, transaction boundaries, typed store contracts, audit coupling, and fail-closed production readiness.",
    minutes: 210,
    prerequisites: ["schema-migrations"],
    objectives: ["Read store interfaces and adapters", "Choose atomic units", "Test adapter parity"],
    concepts: ["Dependency inversion", "Relational command atomicity", "Production versus local adapter guarantees"],
    sources: [
      { path: "lib/persistence/store-adapter.ts", purpose: "Adapter selection policy" },
      { path: "lib/pipeline/referral-store.ts", purpose: "Referral store contract and implementations" },
      { path: "lib/pipeline/workflow-store.ts", purpose: "Workflow store" },
      { path: "lib/assessment/assessment-store.ts", purpose: "Assessment store" },
      { path: "lib/pipeline/user-workspace-state-store.ts", purpose: "Per-user state store" },
    ],
    trace: ["Compare local and PostgreSQL behavior for create, patch, conflict, and delete", "List which audit and version facts share each transaction", "Find every production readiness guard that prevents local-only persistence"],
    lab: {
      title: "Certify adapter parity",
      scenario: "A feature passes local tests but behaves differently with PostgreSQL under a conflict.",
      instructions: ["Define the observable store contract", "Create a parity matrix for success and failure", "Choose fixtures that exercise real PostgreSQL semantics"],
      evidencePrompt: "Provide the adapter contract and parity test matrix, including versions, audit, errors, and retries.",
      acceptanceCriteria: ["Local success cannot weaken production rules", "Conflict semantics match", "PostgreSQL-specific behavior has live fixtures"],
    },
    check: {
      prompt: "Should a database transaction stay open while waiting for Blob upload?",
      options: ["No", "Always", "Only for PDFs"],
      answer: 0,
      explanation: "Slow external work should use durable handoff and reconciliation rather than holding relational locks.",
    },
  },
  {
    id: "concurrency-idempotency",
    trackId: "data",
    number: 20,
    level: "advanced",
    title: "Concurrency, versions, locks, and idempotency",
    summary: "Prevent lost updates, duplicate commands, duplicate packets, stale terminal writes, lease races, and cross-instance inconsistency.",
    minutes: 180,
    prerequisites: ["stores-transactions"],
    objectives: ["Explain record and section versions", "Choose lock scope", "Design idempotent retries"],
    concepts: ["Optimistic concurrency", "Advisory and row-level locking", "Logical mutation identity"],
    sources: [
      { path: "lib/pipeline/referral-sections.ts", purpose: "Section version ownership" },
      { path: "lib/pipeline/editing-presence.ts", purpose: "Presence leases" },
      { path: "database/migrations/0005_collaboration.sql", purpose: "Collaboration schema" },
      { path: "scripts/postgres-concurrency-certification.mjs", purpose: "Live concurrency certification" },
      { path: "tests/e2e/operational/concurrent-referral-edits.scaffold.spec.ts", purpose: "Multi-operator browser scenario" },
    ],
    trace: ["Model same-section and disjoint-section edits", "Trace duplicate mutation IDs before and after commit", "Explain lease expiry and stale-attempt rejection"],
    lab: {
      title: "Run a two-operator concurrency review",
      scenario: "Two coordinators edit identity and documents while a worker reports extraction results and a supervisor decides.",
      instructions: ["Order possible interleavings", "Identify allowed disjoint commits and rejected stale writes", "Specify retry and user reconciliation"],
      evidencePrompt: "Document the concurrency timeline, versions, locks, accepted writes, rejected writes, and recovery UI.",
      acceptanceCriteria: ["No lost update", "Terminal human truth wins", "Retry rereads rather than blindly resubmits"],
      commands: ["npm run database:concurrency", "npm run check:collaboration-load"],
    },
    check: {
      prompt: "What do section versions permit?",
      options: ["Safe disjoint edits with conflict detection", "Unlimited overwrites", "Skipping authorization"],
      answer: 0,
      explanation: "Section versions narrow conflict scope while preserving stale-write detection.",
    },
  },
  {
    id: "identity-matching-reconciliation",
    trackId: "data",
    number: 21,
    level: "advanced",
    title: "Canonical identity, matching, and reconciliation",
    summary: "Prevent silent person merges and splits across referrals, clinical census, assessments, imported history, and external client identifiers.",
    minutes: 180,
    prerequisites: ["concurrency-idempotency"],
    objectives: ["Explain canonical and provisional identity", "Design collision-safe matching", "Use reconciliation rather than silent merge"],
    concepts: ["Deterministic keys and ambiguity", "Human-reviewed resident links", "Cross-system evidence and provenance"],
    sources: [
      { path: "lib/pipeline/master-record-matching.ts", purpose: "Master record matching rules" },
      { path: "lib/pipeline/resident-link-store.ts", purpose: "Reviewed identity link persistence" },
      { path: "lib/assessment/assessment-client-identity.ts", purpose: "Assessment canonical identity resolution" },
      { path: "lib/pipeline/referral-clinical-reconciliation.ts", purpose: "Referral and clinical record reconciliation" },
      { path: "scripts/master-dataset-merge-certification.mjs", purpose: "Planted collision certification" },
    ],
    trace: ["Follow a referral identity into a canonical clinical client link", "List ambiguity and DOB-conflict outcomes", "Explain why name plus DOB still needs provenance and review"],
    lab: {
      title: "Recover a planted collision cohort",
      scenario: "The dataset contains same-name clients, DOB conflicts, duplicate packets, and face sheets without admissions.",
      instructions: ["Define exact expected matches, non-matches, and review cases", "Choose authoritative evidence", "Specify metrics that reveal merge quality without PHI"],
      evidencePrompt: "Provide the planted cohort, exact expected recovery, ambiguous cases, and assertions that detect silent merge errors.",
      acceptanceCriteria: ["False merges and false splits are measured", "Ambiguity never silently selects a client", "Evidence remains inspectable"],
      commands: ["npm run certify:master-merge", "npm run check:allo-import-identity"],
    },
    check: {
      prompt: "What is the safe outcome for two plausible canonical client matches?",
      options: ["Pick the first", "Create an explicit review case", "Average identifiers"],
      answer: 1,
      explanation: "Ambiguity must remain visible and reviewed; a silent merge contaminates every downstream record.",
    },
  },
  {
    id: "query-performance-retention",
    trackId: "data",
    number: 22,
    level: "advanced",
    title: "Query plans, retention, backup, and restore",
    summary: "Keep large datasets fast and recoverable with indexes, bounded queries, capacity models, retention policy, backups, and certified restores.",
    minutes: 180,
    prerequisites: ["identity-matching-reconciliation"],
    objectives: ["Read a query plan", "Explain retention and purge", "Distinguish backup from recovery"],
    concepts: ["Planner evidence and performance budgets", "Retention as a data lifecycle", "RPO, RTO, and restore certification"],
    sources: [
      { path: "scripts/query-plan-audit.mjs", purpose: "Static query-plan coverage" },
      { path: "scripts/postgres-query-plan-fixtures.mjs", purpose: "Live planner assertions" },
      { path: "lib/pipeline/referral-retention.ts", purpose: "Referral retention policy" },
      { path: "scripts/database-backup.mjs", purpose: "Guarded logical backup" },
      { path: "scripts/database-restore-verify.mjs", purpose: "Disposable restore proof" },
      { path: "docs/DATABASE_RECOVERY.md", purpose: "Recovery ownership and objectives" },
    ],
    trace: ["Connect high-volume queries to supporting indexes", "Follow trash eligibility through purge", "Walk backup creation, integrity, restore, and application verification"],
    lab: {
      title: "Prepare for 10x data volume",
      scenario: "Referral, document, and audit volume grows tenfold while the service must retain predictable latency and recoverability.",
      instructions: ["Identify top query and storage risks", "Set measurable budgets and capacity signals", "Define restore evidence and escalation thresholds"],
      evidencePrompt: "Write the query, capacity, retention, backup, and restore plan with explicit budgets and owners.",
      acceptanceCriteria: ["Plans use measured evidence", "Retention does not delete active truth", "Restore success includes application-level verification"],
      commands: ["npm run database:query-plans", "npm run database:capacity", "npm run database:restore:verify"],
    },
    check: {
      prompt: "When does a backup become proven recovery?",
      options: ["When the file exists", "After a verified restore drill", "After compression"],
      answer: 1,
      explanation: "Only a restore drill proves the backup, schema, credentials, and operating procedure can recover the system.",
    },
  },
  {
    id: "upload-storage",
    trackId: "documents-ai",
    number: 23,
    level: "advanced",
    title: "Upload reservation and immutable Blob storage",
    summary: "Understand direct uploads, opaque paths, hashes, completion sentinels, malware gates, preview ranges, immutable raw sources, and storage reconciliation.",
    minutes: 180,
    prerequisites: ["query-performance-retention"],
    objectives: ["Trace reservation to completion", "Protect source bytes and paths", "Recover cross-system partial writes"],
    concepts: ["Signed direct upload", "Immutable raw source of truth", "Completion, integrity, and reconciliation"],
    sources: [
      { path: "app/api/uploads/create-url/route.ts", purpose: "Upload reservation" },
      { path: "app/api/uploads/complete/route.ts", purpose: "Upload completion" },
      { path: "lib/extraction/azure-blob.ts", purpose: "Azure Blob adapter" },
      { path: "lib/extraction/blob-paths.ts", purpose: "Opaque Blob key construction" },
      { path: "lib/extraction/http-byte-range.ts", purpose: "Bounded preview ranges" },
      { path: "lib/extraction/durable-upload-reconciliation.ts", purpose: "Cross-store reconciliation" },
    ],
    trace: ["Follow filename, bytes, hash, opaque path, and completion state separately", "Identify every preview authorization and malware gate", "Model Blob success with database finalization failure and the inverse"],
    lab: {
      title: "Threat-model packet storage",
      scenario: "Users upload duplicate names, malformed PDFs, oversized files, traversal filenames, and interrupted transfers.",
      instructions: ["Map each input to a control", "Define honest durable states", "Specify idempotent retry and reconciliation"],
      evidencePrompt: "Provide the upload state machine, threat controls, partial-failure matrix, and operator recovery actions.",
      acceptanceCriteria: ["Original names never become trusted paths", "Reservation is not treated as completion", "Raw sources remain immutable"],
    },
    check: {
      prompt: "Why upload packet bytes directly to Blob?",
      options: ["To avoid holding Next.js on large binary transfers", "To skip authentication", "To make raw files mutable"],
      answer: 0,
      explanation: "Signed direct upload keeps large bytes off serverless request paths while preserving authenticated reservation and completion.",
    },
  },
  {
    id: "extraction-worker",
    trackId: "documents-ai",
    number: 24,
    level: "advanced",
    title: "Normalization, extraction workers, leases, and callbacks",
    summary: "Follow page manifests through normalization, provider routing, schema-constrained extraction, bounded retries, leases, stale-attempt rejection, and callback validation.",
    minutes: 210,
    prerequisites: ["upload-storage"],
    objectives: ["Trace asynchronous job state", "Validate model output", "Explain lease and retry safety"],
    concepts: ["Page-level normalization and manifests", "Confidence-based provider escalation", "At-least-once processing with idempotent state"],
    sources: [
      { path: "lib/extraction/document-processing.ts", purpose: "Durable document-processing orchestration" },
      { path: "lib/extraction/processing-worker.ts", purpose: "Worker claim and execution" },
      { path: "lib/extraction/extraction-service.ts", purpose: "Extraction provider orchestration" },
      { path: "lib/extraction/worker-report-validation.ts", purpose: "Callback validation" },
      { path: "databricks/pipeline_extraction_worker.py", purpose: "Databricks worker contract" },
      { path: "app/api/internal/extraction/report/route.ts", purpose: "Worker callback boundary" },
    ],
    trace: ["Trace queued, claimed, processing, retry, complete, and dead-letter states", "Show where page order and attempt identity are enforced", "Explain provider output validation before durable candidate writes"],
    lab: {
      title: "Analyze duplicate and late worker delivery",
      scenario: "A lease expires, a second worker succeeds, and the first worker reports later with different values.",
      instructions: ["Order leases and attempts", "Choose which callback may commit", "Define metrics, audit, and recovery for the rejected callback"],
      evidencePrompt: "Document the worker timeline, idempotency keys, stale-attempt rule, accepted state, and observable signals.",
      acceptanceCriteria: ["The late attempt cannot overwrite current truth", "Retry is bounded", "Provider output remains untrusted until validated"],
      commands: ["npm run check:extraction-worker", "npm run check:extraction"],
    },
    check: {
      prompt: "What delivery guarantee should the worker design tolerate?",
      options: ["At-least-once with idempotency", "Exactly once by assumption", "No retries"],
      answer: 0,
      explanation: "Distributed job delivery can repeat; attempt identity and idempotent state make repetition safe.",
    },
  },
  {
    id: "provenance-review",
    trackId: "documents-ai",
    number: 25,
    level: "advanced",
    title: "Extraction candidates, provenance, and human review",
    summary: "Preserve document, page, bounding box, method, confidence, conflicts, reviewer actions, and accepted values through every merge and downstream handoff.",
    minutes: 180,
    prerequisites: ["extraction-worker"],
    objectives: ["Separate candidate from fact", "Resolve disagreements safely", "Measure reviewer quality"],
    concepts: ["Field-level evidence provenance", "Conflict-first merge behavior", "Human approval as a measurable control"],
    sources: [
      { path: "components/pipeline/PacketExtractionReview.tsx", purpose: "Reviewer evidence UI" },
      { path: "app/api/packets/[packetId]/fields/[fieldKey]/review/route.ts", purpose: "Review command" },
      { path: "app/api/packets/[packetId]/evidence/[fieldKey]/route.ts", purpose: "Evidence projection" },
      { path: "lib/extraction/local-packet-evidence.ts", purpose: "Local evidence model" },
      { path: "database/migrations/0004_document_processing.sql", purpose: "Candidate and review schema" },
    ],
    trace: ["Follow one value from page coordinates to accepted fact", "Model two-page disagreement and reviewer resolution", "Identify evidence that must remain after downstream assessment seeding"],
    lab: {
      title: "Review an identity disagreement",
      scenario: "The face sheet and later clinical note disagree on middle initial, DOB format, and medication dosage.",
      instructions: ["Preserve all candidates and evidence", "Classify normalization versus real conflict", "Define reviewer decisions and audit events"],
      evidencePrompt: "Record the candidate set, normalization rules, conflicts, reviewer evidence, and accepted or null outcomes.",
      acceptanceCriteria: ["No first-page-wins rule", "Null is allowed when evidence is insufficient", "Every accepted field retains source provenance"],
    },
    check: {
      prompt: "What is safest when a required handwritten value is illegible?",
      options: ["Guess the likely value", "Store null with a review flag", "Use the filename"],
      answer: 1,
      explanation: "An explicit unknown with evidence is safer than fabricated clinical data.",
    },
  },
  {
    id: "quality-backlog-recovery",
    trackId: "documents-ai",
    number: 26,
    level: "owner",
    title: "Extraction quality, backlog processing, and recovery",
    summary: "Measure field-level quality on a labeled corpus, route expensive fallback selectively, process a 100,000-page backlog resumably, and operate weekly steady-state ingestion.",
    minutes: 180,
    prerequisites: ["provenance-review"],
    objectives: ["Define useful extraction metrics", "Design resumable batch processing", "Recover dead letters and inconsistent storage"],
    concepts: ["Deep and wide labeled corpora", "Precision, recall, provenance, and correction cost", "Batch manifests, checkpoints, and replay"],
    sources: [
      { path: "scripts/extraction-quality-score.mjs", purpose: "Golden-corpus scoring" },
      { path: "scripts/extraction-corpus-readiness.mjs", purpose: "Corpus readiness gate" },
      { path: "scripts/create-batch-manifest.mjs", purpose: "Backlog manifest generation" },
      { path: "scripts/backlog-rehearsal.mjs", purpose: "Resumable synthetic backlog" },
      { path: "scripts/storage-consistency-replay.mjs", purpose: "Storage/database consistency replay" },
      { path: "docs/REFERRAL_PACKET_INGESTION_RUNBOOK.md", purpose: "Backlog and steady-state operations" },
    ],
    trace: ["Explain deep provenance labels versus wide value-only labels", "Follow a batch item through checkpoint, retry, dead letter, and replay", "Connect quality thresholds to provider-routing cost"],
    lab: {
      title: "Plan backlog plus steady state",
      scenario: "Process 100,000 digitized pages once, then maintain roughly 500 new pages each week without losing source truth.",
      instructions: ["Define inventory, dedupe, manifests, batches, checkpoints, and rate limits", "Set quality gates and fallback routing", "Design reconciliation, exception review, and cost reporting"],
      evidencePrompt: "Provide the complete backlog and weekly operating plan with capacity, quality, recovery, and cost controls.",
      acceptanceCriteria: ["Every item is resumable and idempotent", "Quality is measured on labeled evidence", "Backlog and weekly paths converge on one canonical pipeline"],
      commands: ["npm run check:extraction-corpus", "npm run check:backlog-rehearsal", "npm run check:storage-consistency"],
    },
    check: {
      prompt: "Why is a 25-packet corpus insufficient as the only accuracy gate?",
      options: ["Its confidence intervals are too wide", "It contains too many pages", "It prevents OCR"],
      answer: 0,
      explanation: "A small deep set supports provenance tests, but a wider labeled set is needed for useful field-level confidence.",
    },
  },
  {
    id: "clinical-adapter-profiles",
    trackId: "clinical",
    number: 27,
    level: "advanced",
    title: "Clinical adapters, census, and unified profiles",
    summary: "Understand governed reads from the clinical platform, canonical contracts, demo blocking, resident links, unified profiles, census, and aggregate reconciliation.",
    minutes: 180,
    prerequisites: ["quality-backlog-recovery"],
    objectives: ["Trace a governed clinical read", "Explain canonical profile joins", "Keep demo and production data separate"],
    concepts: ["Server-only upstream adapters", "Canonical client identity", "Bounded DTOs and aggregate reconciliation"],
    sources: [
      { path: "lib/clinical/clinical-data.ts", purpose: "Production clinical adapter" },
      { path: "lib/clinical/clinical-contracts.ts", purpose: "Validated clinical DTOs" },
      { path: "lib/clinical/demo-clinical-data.ts", purpose: "Production-blocked demo adapter" },
      { path: "lib/pipeline/unified-profile.ts", purpose: "Cross-system profile projection" },
      { path: "app/api/clinical/census/route.ts", purpose: "Census API boundary" },
      { path: "app/api/profiles/[residentKey]/route.ts", purpose: "Unified profile boundary" },
    ],
    trace: ["Follow an authenticated clinical request through contract validation", "Map referral, resident link, canonical client, assessment, and census identity", "Identify fail-closed behavior when upstream data is unavailable or ambiguous"],
    lab: {
      title: "Diagnose a profile mismatch",
      scenario: "A referral appears under one spelling while census and history suggest two possible residents.",
      instructions: ["Trace all identity evidence", "Prevent a silent profile join", "Define review and downstream visibility"],
      evidencePrompt: "Document the identity graph, ambiguity result, reviewer action, and what each UI/API may safely display.",
      acceptanceCriteria: ["No unreviewed canonical link", "Upstream failure is not replaced with demo data", "DTOs expose only required fields"],
    },
    check: {
      prompt: "What should production do when the clinical backend is unavailable?",
      options: ["Silently use demo records", "Return a bounded unavailable state", "Invent census"],
      answer: 1,
      explanation: "Production must fail honestly rather than substitute synthetic or stale ungoverned clinical truth.",
    },
  },
  {
    id: "assessment-schema-ownership",
    trackId: "clinical",
    number: 28,
    level: "advanced",
    title: "Assessment schema, sections, and field ownership",
    summary: "Master the canonical assessment field registry, aliases, workbook import, section versions, packet-seeded evidence, operator answers, and completion rules.",
    minutes: 180,
    prerequisites: ["clinical-adapter-profiles"],
    objectives: ["Navigate the full field schema", "Distinguish field owners", "Validate workbook coverage"],
    concepts: ["Canonical field registry and aliases", "Section-scoped collaboration", "Seeded evidence versus assessor-owned answers"],
    sources: [
      { path: "lib/assessment/assessment-tool-schema.ts", purpose: "Canonical assessment field registry" },
      { path: "lib/assessment/assessment-interview-schema.ts", purpose: "Interview structure" },
      { path: "lib/assessment/assessment-field-ownership.ts", purpose: "Field ownership policy" },
      { path: "lib/assessment/assessment-sections.ts", purpose: "Section version model" },
      { path: "lib/assessment/assessment-workbook-contract.ts", purpose: "Workbook coverage contract" },
      { path: "lib/assessment/assessment-completion.ts", purpose: "Completion rules" },
    ],
    trace: ["Classify every assessment field by section and owner", "Follow packet seed, imported workbook, and assessor edit precedence", "Explain completion without conflating required, optional, and not-applicable"],
    lab: {
      title: "Add a hypothetical assessment field safely",
      scenario: "Clinical leadership requests a new structured post-assessment reason field.",
      instructions: ["Choose canonical key, section, owner, validation, and aliases", "Trace UI, API, store, migration, import, completion, and export", "Define compatibility and regression tests"],
      evidencePrompt: "Provide the complete field-change dossier and justify ownership, validation, persistence, and backward compatibility.",
      acceptanceCriteria: ["One canonical key exists", "Ownership is explicit", "Import and completion behavior are tested"],
    },
    check: {
      prompt: "Does packet-seeded assessment data mean the assessor already answered the interview?",
      options: ["No", "Yes", "Only for names"],
      answer: 0,
      explanation: "Seeded referral evidence remains distinguishable from assessment-owned interview findings.",
    },
  },
  {
    id: "assessment-lifecycle",
    trackId: "clinical",
    number: 29,
    level: "advanced",
    title: "Assessment lifecycle and immutable clinical history",
    summary: "Own assignment, draft import, Zoom schedule, start, section edits, completion, signature, addenda, recommendation, and versioned history.",
    minutes: 210,
    prerequisites: ["assessment-schema-ownership"],
    objectives: ["Trace every lifecycle command", "Protect assessor attribution", "Use append-only corrections"],
    concepts: ["Explicit lifecycle state", "Assessor-of-record and supervisor coverage", "Immutable signature plus addendum"],
    sources: [
      { path: "lib/assessment/assessment-records.ts", purpose: "Assessment lifecycle records" },
      { path: "lib/assessment/assessment-lifecycle-validation.ts", purpose: "Lifecycle validation" },
      { path: "lib/assessment/assessment-store.ts", purpose: "Transactional persistence" },
      { path: "app/api/assessments/[assessmentId]/schedule/route.ts", purpose: "Scheduling command" },
      { path: "app/api/assessments/[assessmentId]/start/route.ts", purpose: "Start command" },
      { path: "app/api/assessments/[assessmentId]/sign/route.ts", purpose: "Signature command" },
      { path: "app/api/assessments/[assessmentId]/addenda/route.ts", purpose: "Addendum command" },
    ],
    trace: ["Build the lifecycle state and actor table", "Follow attribution through reassignment and supervisor coverage", "Explain exact conflict behavior for signed and amended assessments"],
    lab: {
      title: "Audit assessment timing and attribution",
      scenario: "An assessment is prepared by one coordinator, reassigned, conducted by an assessor, signed, then corrected by addendum.",
      instructions: ["Assign actor and timestamp ownership for every event", "Calculate duration boundaries", "Protect original signed content and correction history"],
      evidencePrompt: "Provide the event ledger, timing calculation, assessor-of-record result, and immutable correction chain.",
      acceptanceCriteria: ["Preparation is not performance time", "Credit follows the correct assessor", "Signed rows are never rewritten"],
      commands: ["npm run check:assessor-workflow", "npm run check:assessment-workbook"],
    },
    check: {
      prompt: "How is a signed assessment corrected?",
      options: ["Update it in place", "Append an authorized addendum", "Delete it"],
      answer: 1,
      explanation: "An addendum preserves the original signed record, correction, actor, reason, and time.",
    },
  },
  {
    id: "medication-decision-ehr",
    trackId: "clinical",
    number: 30,
    level: "owner",
    title: "Medications, recommendations, decisions, and EHR export",
    summary: "Preserve medication provenance across packet and assessment, keep recommendations separate from decisions, and export only accepted reviewed records to EHR creation.",
    minutes: 180,
    prerequisites: ["assessment-lifecycle"],
    objectives: ["Trace medication ownership", "Protect decision authority", "Define EHR readiness and retry"],
    concepts: ["Medication evidence and assessor confirmation", "Clinical recommendation versus admission authority", "Approval-gated outbox and export"],
    sources: [
      { path: "lib/assessment/assessment-seed.ts", purpose: "Medication evidence seed" },
      { path: "lib/clinical/clinical-value-presentation.ts", purpose: "Clinical value display rules" },
      { path: "app/api/referrals/[referralId]/recommendation/route.ts", purpose: "Recommendation command" },
      { path: "app/api/referrals/[referralId]/decision/route.ts", purpose: "Admission decision command" },
      { path: "lib/integration/client-update-outbox.ts", purpose: "Approval-gated downstream outbox" },
      { path: "lib/integration/client-update-contracts.ts", purpose: "Downstream payload contracts" },
    ],
    trace: ["Trace a medication through extraction, review, seed, assessor confirmation, and export", "List terminal decision authorization and version controls", "Follow queued, sent, failed, and retried EHR handoff states"],
    lab: {
      title: "Certify an accepted-client handoff",
      scenario: "An accepted referral has one unresolved medication conflict and a prior failed EHR delivery attempt.",
      instructions: ["Determine whether export is ready", "Resolve or preserve medication uncertainty correctly", "Design idempotent downstream retry and audit"],
      evidencePrompt: "Provide the readiness decision, blocked fields, resolution path, payload ownership, idempotency key, and retry evidence.",
      acceptanceCriteria: ["Accepted status alone is not enough", "Medication ambiguity is not hidden", "Retry cannot create a duplicate EHR record"],
    },
    check: {
      prompt: "Which referrals belong in the EHR creation export?",
      options: ["Every uploaded packet", "Accepted referrals that satisfy reviewed handoff requirements", "All scheduled assessments"],
      answer: 1,
      explanation: "The export is an accepted-record handoff and must remain gated by reviewed downstream requirements.",
    },
  },
  {
    id: "entra-session",
    trackId: "security",
    number: 31,
    level: "advanced",
    title: "Entra identity, tokens, sessions, and proxy enforcement",
    summary: "Understand tenant, issuer, audience, scope, keys, token verification, encrypted sessions, sign-in flow, protected paths, and internal worker identity.",
    minutes: 180,
    prerequisites: ["medication-decision-ehr"],
    objectives: ["Trace browser sign-in to PipelineUser", "Explain token verification claims", "Separate user and worker authentication"],
    concepts: ["OIDC and JWT verification", "Encrypted HTTP-only session cookies", "Proxy path protection and worker secrets"],
    sources: [
      { path: "lib/auth/entra-client.ts", purpose: "Browser Entra client" },
      { path: "lib/auth/pipeline-auth.ts", purpose: "Token and session verification" },
      { path: "lib/auth/browser-session.ts", purpose: "Browser session behavior" },
      { path: "lib/auth/internal-worker-auth.ts", purpose: "Worker authentication" },
      { path: "proxy.ts", purpose: "Protected path and security headers" },
      { path: "docs/ENTRA_AUTHENTICATION.md", purpose: "Identity deployment runbook" },
    ],
    trace: ["Follow an Entra token into an authenticated Pipeline principal", "List every verified claim and why signature alone is insufficient", "Compare user session, delegated upstream token, and internal worker authentication"],
    lab: {
      title: "Rehearse identity failure modes",
      scenario: "Requests arrive with wrong tenant, audience, scope, expired session, spoofed headers, and missing worker secret.",
      instructions: ["Predict exact deny behavior", "Identify the enforcing code", "Specify PHI-safe diagnostics and readiness signals"],
      evidencePrompt: "Provide the identity failure matrix with expected status, enforcing boundary, and safe operational evidence.",
      acceptanceCriteria: ["Production never trusts arbitrary headers", "Issuer, audience, scope, and expiry are distinct", "Worker and user identities cannot substitute for each other"],
      commands: ["npm run check:access", "npm run check:security"],
    },
    check: {
      prompt: "Is a valid JWT signature enough for access?",
      options: ["No, issuer, audience, scope, time, and identity claims also matter", "Yes", "Only for administrators"],
      answer: 0,
      explanation: "Cryptographic validity does not prove the token was issued for this tenant, app, scope, or current time.",
    },
  },
  {
    id: "authorization-phi",
    trackId: "security",
    number: 32,
    level: "owner",
    title: "Authorization, PHI boundaries, retention, and audit",
    summary: "Apply least privilege to every record and command while keeping logs, metrics, errors, fixtures, previews, exports, and learning evidence free of PHI.",
    minutes: 210,
    prerequisites: ["entra-session"],
    objectives: ["Build complete permission matrices", "Identify every PHI boundary", "Explain audit and retention responsibilities"],
    concepts: ["Role, assignment, resource, and state authorization", "Data minimization and safe DTOs", "Audit evidence without shadow clinical databases"],
    sources: [
      { path: "lib/pipeline/referral-access.ts", purpose: "Referral access policy" },
      { path: "lib/assessment/assessment-access.ts", purpose: "Assessment access policy" },
      { path: "lib/observability/metric-contract.ts", purpose: "PHI-safe metric dimensions" },
      { path: "lib/observability/api-logging.ts", purpose: "Bounded structured logging" },
      { path: "docs/RETENTION_POLICY.md", purpose: "Retention policy" },
      { path: "docs/ABUSE_AND_ALERTING.md", purpose: "Abuse and alerting boundaries" },
    ],
    trace: ["Map every role to permitted reads and mutations", "Inspect all places clinical values cross into client, logs, metrics, exports, or files", "Follow deletion eligibility, audit retention, and restore behavior"],
    lab: {
      title: "Conduct a PHI boundary review",
      scenario: "A developer proposes logging request bodies to debug extraction and adding referral IDs to metric dimensions.",
      instructions: ["Identify privacy, cardinality, and retention risks", "Design safe diagnostics", "Define review checks that prevent recurrence"],
      evidencePrompt: "Write the rejected design analysis and replacement logging, metric, trace, and fixture contracts.",
      acceptanceCriteria: ["No patient identifiers enter telemetry", "Dimensions remain bounded", "Debuggability is preserved through request IDs and typed outcomes"],
    },
    check: {
      prompt: "Which metric dimension is appropriate?",
      options: ["client_name", "referral_id", "outcome=conflict"],
      answer: 2,
      explanation: "A bounded outcome class supports operations without PHI or unbounded cardinality.",
    },
  },
  {
    id: "threat-supply-chain",
    trackId: "security",
    number: 33,
    level: "owner",
    title: "Threat modeling, abuse resistance, and supply chain",
    summary: "Review file attacks, request abuse, overload, dependency integrity, licenses, CI permissions, artifacts, secrets, container boundaries, and release provenance.",
    minutes: 180,
    prerequisites: ["authorization-phi"],
    objectives: ["Threat-model critical journeys", "Explain overload controls", "Verify dependency and artifact provenance"],
    concepts: ["Abuse cases and rate boundaries", "Dependency lockfile and SBOM", "Least-privilege CI and immutable artifacts"],
    sources: [
      { path: "lib/reliability/request-governor.ts", purpose: "Application overload control" },
      { path: "scripts/license-policy-audit.mjs", purpose: "License policy" },
      { path: "scripts/supply-chain-readiness.mjs", purpose: "Supply-chain gate" },
      { path: "scripts/generate-sbom.mjs", purpose: "CycloneDX inventory" },
      { path: "scripts/build-artifact-audit.mjs", purpose: "Bundle and credential marker audit" },
      { path: ".github/workflows/ci.yml", purpose: "CI permission and gate configuration" },
    ],
    trace: ["Threat-model referral creation, file preview, extraction callback, and EHR handoff", "Follow one dependency from lockfile to SBOM and release evidence", "Explain application governor versus edge rate limiting"],
    lab: {
      title: "Build the release threat dossier",
      scenario: "A release adds a PDF dependency, worker callback change, and larger upload limit.",
      instructions: ["Assess dependency, parser, resource, and authentication risk", "Define static, dynamic, and operational controls", "Specify release evidence and rollback triggers"],
      evidencePrompt: "Provide the threat model, control owners, tests, monitoring, and release/rollback evidence.",
      acceptanceCriteria: ["Supply-chain and runtime risks are separate", "Resource exhaustion is bounded", "Every critical control has executable evidence"],
      commands: ["npm run check:supply-chain", "npm run check:licenses", "npm run check:artifacts"],
    },
    check: {
      prompt: "Does an application request governor replace edge rate limiting?",
      options: ["No", "Yes", "Only in development"],
      answer: 0,
      explanation: "Application capacity controls and edge abuse controls protect different boundaries and should be layered.",
    },
  },
  {
    id: "test-assurance",
    trackId: "reliability",
    number: 34,
    level: "owner",
    title: "Testing architecture and assertion power",
    summary: "Choose the smallest truthful test layer, replay real failures, generate state histories, test browsers and PostgreSQL, plant realistic defects, and measure whether controls actually fail.",
    minutes: 240,
    prerequisites: ["threat-supply-chain"],
    objectives: ["Map risks to test layers", "Interpret seeded-defect results", "Design a realistic multi-user demo"],
    concepts: ["Pure contracts, API fixtures, database fixtures, and browser journeys", "Property and stateful testing", "Mutation and seeded-defect effectiveness"],
    sources: [
      { path: "scripts/api-behavior-fixtures.mjs", purpose: "Deterministic API behavior" },
      { path: "scripts/workflow-stateful-fuzz.mjs", purpose: "Generated workflow histories" },
      { path: "scripts/critical-safety-contracts.mjs", purpose: "Clinical and data safety controls" },
      { path: "scripts/seeded-defect-certification.mjs", purpose: "Assertion-power certification" },
      { path: "tests/e2e/pipeline-smoke.spec.ts", purpose: "Integrated operator journeys" },
      { path: "tests/e2e/operational/high-traffic-capacity.scaffold.spec.ts", purpose: "100-user product scenario" },
      { path: "docs/EXTREME_TESTING_PROTOCOL.md", purpose: "Full testing strategy" },
    ],
    trace: ["Classify every test command by the failure it can detect", "Follow one real regression into a permanent replay", "Review seeded defects and identify any surviving safety mutation"],
    lab: {
      title: "Design a 100-user clinical product exercise",
      scenario: "One hundred actors create referrals, upload packets, review extraction, assess, decide, report, and recover from injected failures.",
      instructions: ["Define actor roles and deterministic workload", "Plant concurrency, dependency, and data-integrity faults", "Set pass/fail budgets for correctness, latency, recovery, and PHI safety"],
      evidencePrompt: "Provide the workload model, fault schedule, assertions, budgets, artifacts, and triage ownership.",
      acceptanceCriteria: ["Assertions test product truth, not request count", "Database and browser evidence are included", "The suite's defect-detection power is measured"],
      commands: ["npm run check:platform:fast", "npm run certify:test-effectiveness", "npm run demo:100"],
    },
    check: {
      prompt: "What does seeded-defect certification measure?",
      options: ["Test file count", "Whether controls catch planted realistic defects", "Snapshot size"],
      answer: 1,
      explanation: "A suite is credible when known dangerous changes cause the owning controls to fail.",
    },
  },
  {
    id: "operations-recovery-release",
    trackId: "reliability",
    number: 35,
    level: "owner",
    title: "Observability, capacity, incidents, recovery, and release",
    summary: "Operate queues, latency, conflicts, capacity, alerts, dead letters, storage reconciliation, database restore, release evidence, deployment, and rollback as one owned system.",
    minutes: 240,
    prerequisites: ["test-assurance"],
    objectives: ["Read PHI-safe service signals", "Lead a recovery sequence", "Make an evidence-based release decision"],
    concepts: ["Service-level signals and alert ownership", "Idempotent recovery and reconciliation", "Immutable release evidence and reversible delivery"],
    sources: [
      { path: "lib/observability/pipeline-metrics.ts", purpose: "Operational metrics" },
      { path: "scripts/alerting-readiness.mjs", purpose: "Alert contracts" },
      { path: "scripts/chaos-recovery-replay.mjs", purpose: "Dependency-failure recovery" },
      { path: "scripts/operational-certification.mjs", purpose: "Tiered operational certification" },
      { path: "scripts/release-compatibility.mjs", purpose: "Release compatibility" },
      { path: "scripts/create-release-evidence.mjs", purpose: "Checksummed evidence bundle" },
      { path: "docs/PRODUCTION_DEPLOYMENT_RUNBOOK.md", purpose: "Deployment and rollback" },
      { path: "infra/azure/operational-alerts.bicep", purpose: "Azure alert infrastructure" },
    ],
    trace: ["Connect every alert to metric, threshold, owner, and runbook", "Walk queue backlog, Blob inconsistency, database outage, and auth failure recovery", "Trace commit, build, migration, artifact, deployment, smoke, and rollback evidence"],
    lab: {
      title: "Lead a production incident tabletop",
      scenario: "Extraction queue age rises, Blob reconciliation detects missing objects, and a deployment includes a new migration.",
      instructions: ["Triage impact without exposing PHI", "Choose containment, retry, reconcile, rollback, or forward-fix", "Define proof of recovery and follow-up regression"],
      evidencePrompt: "Write the incident timeline, decisions, owners, commands, recovery evidence, and permanent test additions.",
      acceptanceCriteria: ["Patient data remains protected", "Recovery commands are idempotent", "Service restoration is proven at application and data layers"],
      commands: ["npm run certify:operations:quick", "npm run check:chaos", "npm run check:release"],
    },
    check: {
      prompt: "What does a static infrastructure check prove?",
      options: ["Repository intent is represented", "The live Azure environment is healthy", "A restore succeeded"],
      answer: 0,
      explanation: "Static checks validate declared controls; live credentials, resources, alerts, and recovery require live certification.",
    },
  },
  {
    id: "vertical-change-capstone",
    trackId: "ownership",
    number: 36,
    level: "owner",
    title: "Vertical change, review, and ownership capstone",
    summary: "Complete a small real change with product intent, source trace, architecture, authorization, schema compatibility, tests, observability, rollout, rollback, and teach-back.",
    minutes: 360,
    prerequisites: ["operations-recovery-release"],
    objectives: ["Own a bounded change end to end", "Review for system-wide consequences", "Teach and defend the result"],
    concepts: ["Change dossiers and explicit non-goals", "Characterization before refactoring", "Evidence-based review and operational ownership"],
    sources: [
      { path: "docs/academy/CHANGE_DOSSIER_TEMPLATE.md", purpose: "Change-learning artifact" },
      { path: "docs/REFACTORING_PLAYBOOK.md", purpose: "Safe refactor protocol" },
      { path: "docs/refactoring/REFACTOR_SLICE_TEMPLATE.md", purpose: "Bounded refactor slice" },
      { path: "docs/refactoring/COMPATIBILITY_MATRIX.md", purpose: "Compatibility reasoning" },
      { path: "scripts/ci-change-impact.mjs", purpose: "Change-sensitive assurance selection" },
      { path: "scripts/platform-readiness.mjs", purpose: "Daily readiness bundle" },
    ],
    trace: ["Choose one field, workflow rule, report, or integration behavior and trace every owner", "Characterize current behavior before modifying it", "Map product, UI, API, domain, data, security, test, and operations consequences"],
    lab: {
      title: "Complete the ownership capstone",
      scenario: "Implement one approved, bounded production-style change without weakening any existing invariant.",
      instructions: ["Write intent, non-goals, current trace, and risk matrix", "Implement in an isolated branch with focused tests and migration plan if needed", "Run certification, prepare rollout and rollback, and deliver a ten-minute teach-back"],
      evidencePrompt: "Link or summarize the complete change dossier, diff scope, test evidence, review findings, release plan, rollback, and teach-back.",
      acceptanceCriteria: ["The change is bounded and source-grounded", "Security, concurrency, PHI, and recovery are addressed", "Another engineer can operate and review the result"],
      commands: ["npm run check:refactor-setup", "npm run check:platform:fast", "npm run certify:test-effectiveness", "npm run build"],
    },
    check: {
      prompt: "What demonstrates repository ownership?",
      options: ["Reading every filename once", "Safely changing, proving, operating, recovering, and teaching a vertical slice", "Memorizing line counts"],
      answer: 1,
      explanation: "Ownership is demonstrated through correct changes and recovery evidence, not passive familiarity.",
    },
  },
] as const;

export const academyModules: readonly AcademyModule[] = definitions.map((definition) => ({
  ...definition,
  activities: buildActivities(definition),
}));

export const academyActivityIds = academyModules.flatMap((module) => (
  module.activities.map((activity) => academyActivityKey(module.id, activity.id))
));

export const academyModuleIds = academyModules.map((module) => module.id);

export const academyCompetencies: readonly AcademyCompetency[] = [
  {
    id: "navigate",
    title: "Repository navigator",
    standard: "Find the UI, route, domain, persistence, migration, test, and runbook owner of an unfamiliar behavior without guessing.",
    proof: ["Runtime map from memory", "Every-file atlas drill", "Correct source-owner trace for a surprise behavior"],
    moduleIds: ["system-map", "developer-toolchain", "next-react-runtime"],
  },
  {
    id: "trace",
    title: "End-to-end tracer",
    standard: "Follow values, control, identity, versions, and evidence across browser, server, database, Blob, workers, and external systems.",
    proof: ["Golden referral trace", "Assessment lifecycle ledger", "Distributed upload failure matrix"],
    moduleIds: ["create-referral", "assessment-lifecycle", "upload-storage", "extraction-worker"],
  },
  {
    id: "change",
    title: "Safe contributor",
    standard: "Make a bounded change that preserves validation, authorization, audit, compatibility, concurrency, PHI, and recovery guarantees.",
    proof: ["Approved change dossier", "Focused regression", "Compatibility and rollback evidence"],
    moduleIds: ["schema-migrations", "validation-authorization", "vertical-change-capstone"],
  },
  {
    id: "review",
    title: "Enterprise reviewer",
    standard: "Detect duplicated policy, unsafe trust, silent merge, weak assertions, incompatible schema, and unowned failure paths.",
    proof: ["Authorization matrix", "Seeded-defect analysis", "Identity collision review", "Threat dossier"],
    moduleIds: ["workflow-state", "identity-matching-reconciliation", "threat-supply-chain", "test-assurance"],
  },
  {
    id: "operate",
    title: "Production operator",
    standard: "Use PHI-safe signals to triage, contain, reconcile, restore, verify, and communicate a production failure.",
    proof: ["Incident tabletop", "Restore certification explanation", "Queue and storage reconciliation runbook"],
    moduleIds: ["quality-backlog-recovery", "query-performance-retention", "operations-recovery-release"],
  },
  {
    id: "own",
    title: "System owner and teacher",
    standard: "Design and defend a vertical slice, make the release decision, recover it, and teach another engineer how it works.",
    proof: ["Capstone", "Ten-minute teach-back", "Independent review sign-off"],
    moduleIds: ["vertical-change-capstone"],
  },
] as const;

export function academyActivityKey(moduleId: string, activityId: string) {
  return `${moduleId}:${activityId}`;
}

export function getAcademyModule(moduleId: string) {
  return academyModules.find((module) => module.id === moduleId);
}

export function getAcademyTrack(trackId: string) {
  return academyTracks.find((track) => track.id === trackId);
}

export function academyTotalMinutes() {
  return academyModules.reduce((total, module) => total + module.minutes, 0);
}

function buildActivities(module: AcademyModuleDefinition): readonly AcademyActivity[] {
  const learnMinutes = Math.max(20, Math.round(module.minutes * 0.2));
  const traceMinutes = Math.max(25, Math.round(module.minutes * 0.25));
  const checkMinutes = Math.max(10, Math.round(module.minutes * 0.08));
  const labMinutes = module.minutes - learnMinutes - traceMinutes - checkMinutes;

  return [
    {
      id: "learn",
      moduleId: module.id,
      kind: "learn",
      title: `Learn: ${module.title}`,
      minutes: learnMinutes,
      summary: module.summary,
      instructions: module.concepts,
      sources: module.sources,
    },
    {
      id: "trace",
      moduleId: module.id,
      kind: "source-trace",
      title: "Trace the current implementation",
      minutes: traceMinutes,
      summary: "Read the current source in execution order and record what is authoritative at each boundary.",
      instructions: module.trace,
      sources: module.sources,
      evidencePrompt: "Write the source-backed trace from memory first, then record corrections made after verifying the repository.",
      acceptanceCriteria: ["The trace names concrete symbols or files", "Trust and state ownership are explicit", "At least one failure path is included"],
    },
    {
      id: "lab",
      moduleId: module.id,
      kind: "lab",
      title: module.lab.title,
      minutes: labMinutes,
      summary: module.lab.scenario,
      instructions: module.lab.instructions,
      sources: module.sources,
      evidencePrompt: module.lab.evidencePrompt,
      acceptanceCriteria: module.lab.acceptanceCriteria,
      commands: module.lab.commands,
    },
    {
      id: "check",
      moduleId: module.id,
      kind: "knowledge-check",
      title: "Verify understanding",
      minutes: checkMinutes,
      summary: "Answer the checkpoint and explain why the rejected choices would be unsafe or incorrect.",
      instructions: ["Answer without reopening the source", "Read the explanation", "Return to the trace if your mental model was wrong"],
      sources: module.sources,
      check: module.check,
    },
  ];
}
