begin;

create extension if not exists pgcrypto;
create schema if not exists pipeline;

create table if not exists pipeline.schema_migrations (
  migration_id text primary key,
  applied_at timestamptz not null default now()
);

create table if not exists pipeline.store_revisions (
  store_name text primary key,
  revision bigint not null default 0 check (revision >= 0),
  updated_at timestamptz not null default now()
);

insert into pipeline.store_revisions (store_name)
values ('referrals'), ('assessments')
on conflict (store_name) do nothing;

create table if not exists pipeline.people (
  person_id uuid primary key default gen_random_uuid(),
  external_client_id text unique,
  display_name text not null,
  date_of_birth date,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists pipeline.referrals (
  referral_id bigint generated by default as identity primary key,
  person_id uuid not null references pipeline.people(person_id),
  version integer not null default 1 check (version > 0),
  stage text not null check (stage in (
    'New', 'Packet Needed', 'Packet Review', 'Assessment',
    'Community Review', 'Accepted / Admitted', 'Declined'
  )),
  community text not null,
  owner_id text,
  owner_name text,
  priority text not null default 'standard' check (priority in ('urgent', 'high', 'standard')),
  source text not null default '',
  received_date date,
  due_at timestamptz,
  next_action text,
  tags text[] not null default '{}',
  summary text,
  document_sha256 text check (document_sha256 is null or document_sha256 ~ '^[a-f0-9]{64}$'),
  search_text text not null default '',
  data jsonb not null default '{}',
  closed_at timestamptz,
  created_by text not null,
  created_by_name text not null,
  updated_by text not null,
  updated_by_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists referrals_stage_updated_idx
  on pipeline.referrals(stage, updated_at desc, referral_id desc);
create index if not exists referrals_community_created_idx
  on pipeline.referrals(community, created_at desc, referral_id desc);
create index if not exists referrals_owner_due_idx
  on pipeline.referrals(owner_id, due_at, referral_id)
  where closed_at is null;
create index if not exists referrals_person_idx
  on pipeline.referrals(person_id, created_at desc, referral_id desc);
create index if not exists referrals_tags_gin_idx
  on pipeline.referrals using gin(tags);
create unique index if not exists referrals_document_sha256_unique_idx
  on pipeline.referrals(document_sha256)
  where document_sha256 is not null;
create extension if not exists pg_trgm;
create index if not exists referrals_search_text_trgm_idx
  on pipeline.referrals using gin(search_text gin_trgm_ops);

create table if not exists pipeline.referral_fields (
  referral_field_id uuid primary key default gen_random_uuid(),
  referral_id bigint not null references pipeline.referrals(referral_id) on delete cascade,
  field_key text not null,
  proposed_value jsonb,
  final_value jsonb,
  confidence numeric(5,4) check (confidence between 0 and 1),
  review_status text not null check (review_status in ('pending', 'confirmed', 'edited', 'rejected')),
  source_document_id uuid,
  source_page integer check (source_page is null or source_page > 0),
  evidence_blob_key text,
  reviewer_id text,
  reviewed_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (referral_id, field_key)
);

create index if not exists referral_fields_review_idx
  on pipeline.referral_fields(referral_id, review_status, field_key);

create table if not exists pipeline.documents (
  document_id uuid primary key default gen_random_uuid(),
  referral_id bigint references pipeline.referrals(referral_id) on delete cascade,
  person_id uuid references pipeline.people(person_id),
  category text not null,
  file_name text not null,
  content_type text not null,
  byte_size bigint not null check (byte_size >= 0),
  sha256 text not null check (sha256 ~ '^[a-f0-9]{64}$'),
  blob_container text not null,
  blob_key text not null,
  processing_status text not null check (processing_status in (
    'reserved', 'uploaded', 'processing', 'ready_for_review', 'reviewed', 'failed', 'quarantined'
  )),
  uploaded_by text not null,
  uploaded_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (blob_container, blob_key)
);

create unique index if not exists documents_sha256_referral_unique_idx
  on pipeline.documents(referral_id, sha256)
  where referral_id is not null and processing_status <> 'quarantined';
create index if not exists documents_person_date_idx
  on pipeline.documents(person_id, uploaded_at desc, document_id);

alter table pipeline.referral_fields
  drop constraint if exists referral_fields_source_document_id_fkey;
alter table pipeline.referral_fields
  add constraint referral_fields_source_document_id_fkey
  foreign key (source_document_id) references pipeline.documents(document_id);

create table if not exists pipeline.extraction_jobs (
  extraction_job_id uuid primary key default gen_random_uuid(),
  document_id uuid not null references pipeline.documents(document_id) on delete cascade,
  job_type text not null check (job_type in ('referral_packet', 'assessment_workbook', 'document_preview')),
  status text not null check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  max_attempts integer not null default 5 check (max_attempts between 1 and 20),
  provider_job_id text,
  error_code text,
  queued_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists extraction_jobs_queue_idx
  on pipeline.extraction_jobs(status, queued_at, extraction_job_id)
  where status in ('queued', 'running');

create table if not exists pipeline.assessments (
  assessment_id text primary key,
  referral_id bigint not null references pipeline.referrals(referral_id) on delete cascade,
  resident_key text,
  resident_number text,
  assessment_date date,
  assessor_id text,
  assessor_name text,
  status text not null check (status in ('draft', 'needs_review', 'complete')),
  data jsonb not null default '{}',
  version integer not null default 1 check (version > 0),
  completed_at timestamptz,
  created_by text not null,
  created_by_name text not null,
  updated_by text not null,
  updated_by_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists assessments_referral_date_idx
  on pipeline.assessments(referral_id, assessment_date desc, created_at desc);
create index if not exists assessments_resident_number_date_idx
  on pipeline.assessments(resident_number, assessment_date desc, created_at desc)
  where resident_number is not null;
create index if not exists assessments_resident_key_date_idx
  on pipeline.assessments(resident_key, assessment_date desc, created_at desc)
  where resident_key is not null;

create table if not exists pipeline.assessment_field_provenance (
  provenance_id uuid primary key default gen_random_uuid(),
  assessment_id text not null references pipeline.assessments(assessment_id) on delete cascade,
  field_key text not null,
  source_field_key text not null,
  source_file text,
  source_page integer check (source_page is null or source_page > 0),
  confidence numeric(5,4) check (confidence between 0 and 1),
  evidence_blob_key text,
  review_status text not null check (review_status in ('pending', 'accepted', 'edited', 'rejected')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists assessment_provenance_field_idx
  on pipeline.assessment_field_provenance(assessment_id, field_key, created_at);

create table if not exists pipeline.assessment_unmapped_fields (
  unmapped_field_id uuid primary key default gen_random_uuid(),
  assessment_id text not null references pipeline.assessments(assessment_id) on delete cascade,
  source_field_key text not null,
  source_value jsonb,
  reason text not null,
  source_file text,
  source_page integer check (source_page is null or source_page > 0),
  confidence numeric(5,4) check (confidence between 0 and 1),
  evidence_blob_key text,
  review_status text not null default 'pending' check (review_status in ('pending', 'accepted', 'edited', 'rejected')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by text,
  mapped_field_key text
);

create index if not exists assessment_unmapped_open_idx
  on pipeline.assessment_unmapped_fields(assessment_id, created_at)
  where resolved_at is null;

create table if not exists pipeline.work_items (
  work_item_id uuid primary key default gen_random_uuid(),
  referral_id bigint not null references pipeline.referrals(referral_id) on delete cascade,
  person_id uuid not null references pipeline.people(person_id),
  type text not null,
  label text not null,
  gate text not null check (gate in ('pre_assessment', 'admission_decision', 'move_in', 'ehr_export')),
  status text not null check (status in ('needed', 'requested', 'received', 'reviewed', 'waived', 'expired')),
  owner_id text,
  owner_name text,
  due_at timestamptz,
  next_action text not null,
  blocker boolean not null default true,
  evidence_document_id uuid references pipeline.documents(document_id),
  waiver_reason text,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists work_items_action_queue_idx
  on pipeline.work_items(status, due_at, owner_id, referral_id)
  where status not in ('reviewed', 'waived');
create index if not exists work_items_person_idx
  on pipeline.work_items(person_id, updated_at desc, work_item_id);

create table if not exists pipeline.admission_decisions (
  decision_id uuid primary key default gen_random_uuid(),
  referral_id bigint not null unique references pipeline.referrals(referral_id) on delete cascade,
  outcome text not null check (outcome in ('accepted', 'declined')),
  reason_code text,
  reason_note text,
  decided_by text not null,
  decided_at timestamptz not null default now(),
  version integer not null default 1 check (version > 0)
);

create table if not exists pipeline.resident_links (
  resident_link_id uuid primary key default gen_random_uuid(),
  person_id uuid not null references pipeline.people(person_id) on delete cascade,
  referral_id bigint references pipeline.referrals(referral_id) on delete set null,
  resident_key text not null,
  resident_number text,
  community_id text not null,
  status text not null check (status in ('candidate', 'confirmed', 'rejected')),
  match_method text not null check (match_method in ('resident_number_exact', 'manual', 'imported')),
  match_confidence numeric(5,4) check (match_confidence between 0 and 1),
  version integer not null default 1 check (version > 0),
  created_by text not null,
  created_by_name text not null,
  reviewed_by text,
  reviewed_by_name text,
  review_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists resident_links_confirmed_resident_unique_idx
  on pipeline.resident_links(resident_key)
  where status = 'confirmed';
create unique index if not exists resident_links_confirmed_person_unique_idx
  on pipeline.resident_links(person_id)
  where status = 'confirmed';
create unique index if not exists resident_links_active_pair_unique_idx
  on pipeline.resident_links(person_id, resident_key)
  where status <> 'rejected';
create index if not exists resident_links_candidate_resident_number_idx
  on pipeline.resident_links(resident_number, community_id, created_at desc)
  where resident_number is not null and status = 'candidate';
create index if not exists resident_links_referral_idx
  on pipeline.resident_links(referral_id, created_at desc)
  where referral_id is not null;

create table if not exists pipeline.audit_events (
  audit_event_id uuid primary key default gen_random_uuid(),
  entity_type text not null,
  entity_id text not null,
  action text not null,
  actor_id text not null,
  actor_name text not null,
  from_version integer,
  to_version integer,
  changed_fields text[] not null default '{}',
  before_values jsonb,
  after_values jsonb,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists audit_events_entity_idx
  on pipeline.audit_events(entity_type, entity_id, created_at desc, audit_event_id desc);
create index if not exists audit_events_actor_idx
  on pipeline.audit_events(actor_id, created_at desc, audit_event_id desc);

create table if not exists pipeline.idempotency_keys (
  scope text not null,
  mutation_id text not null,
  entity_type text not null,
  entity_id text not null,
  created_at timestamptz not null default now(),
  primary key (scope, mutation_id)
);

insert into pipeline.schema_migrations (migration_id)
values ('0001_pipeline_core')
on conflict (migration_id) do nothing;

revoke all on schema pipeline from public;
revoke all on all tables in schema pipeline from public;
revoke all on all sequences in schema pipeline from public;

commit;
