#!/usr/bin/env node
// Dark mode for the redesign (docs/design/DECISIONS.md, "Dark mode").
//
// The design tokens get hand-tuned dark values in app/design-dark.css. Everything that still
// hardcodes a light color (Tailwind arbitrary classes in components, hex values in stylesheets,
// SVG fill attributes) gets a generated dark counterpart from this script, chosen by the color's
// role (background, text, or border) in OKLCH so hue is kept and contrast flips.
//
// Output, all scoped to html[data-design="v2"] under prefers-color-scheme: dark:
//   - app/design-dark.generated.css: component classes and SVG attributes
//   - a marked block appended to each stylesheet (CSS module classes are local to their file)
// Rules for the current design (html:not([data-design="v2"])) are never touched.
//
// Usage: node scripts/design-dark.mjs          regenerate
//        node scripts/design-dark.mjs --check  exit 1 if anything is stale
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import postcss from "postcss";

const root = new URL("..", import.meta.url).pathname;
const check = process.argv.includes("--check");
const START = "/* design:dark generated by scripts/design-dark.mjs; do not edit below this line */";
const WRAP = ':where(html[data-design="v2"])';
const MEDIA = "(prefers-color-scheme: dark)";

// ---------- color math (OKLCH) ----------
const toLinear = (c) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const fromLinear = (c) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);
function rgbToOklch([r, g, b]) {
  const [lr, lg, lb] = [r, g, b].map((v) => toLinear(v / 255));
  const l = Math.cbrt(0.4122214708 * lr + 0.5363325363 * lg + 0.0514459929 * lb);
  const m = Math.cbrt(0.2119034982 * lr + 0.6806995451 * lg + 0.1073969566 * lb);
  const s = Math.cbrt(0.0883024619 * lr + 0.2817188376 * lg + 0.6299787005 * lb);
  const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return [L, Math.hypot(A, B), Math.atan2(B, A)];
}
function oklchToRgb([L, C, h]) {
  const A = C * Math.cos(h), B = C * Math.sin(h);
  const l = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3;
  const m = (L - 0.1055613458 * A - 0.0638541728 * B) ** 3;
  const s = (L - 0.0894841775 * A - 1.291485548 * B) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ].map(fromLinear);
}
function toHex([L, C, h], alpha = 1) {
  let rgb = oklchToRgb([L, C, h]);
  for (let c = C; rgb.some((v) => v < -0.0005 || v > 1.0005) && c > 0; c -= 0.004) rgb = oklchToRgb([L, Math.max(0, c - 0.004), h]);
  const hex = rgb.map((v) => Math.round(Math.min(1, Math.max(0, v)) * 255).toString(16).padStart(2, "0")).join("");
  return alpha >= 1 ? `#${hex}` : `#${hex}${Math.round(alpha * 255).toString(16).padStart(2, "0")}`;
}
const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, v));

// Role maps. Light surfaces become dark surfaces a step above the page (cards lift in the dark);
// dark ink becomes light ink; colored accents keep their hue and gain lightness to stay legible.
const roles = {
  bg([L, C, h]) {
    if (L >= 0.8) return [0.235 + (1 - L) * 0.9, Math.min(C * 1.1, 0.06), h];
    if (L >= 0.35) return [L, C * 0.95, h];
    return [0.3 + (0.35 - L) * 0.2, C, h];
  },
  text([L, C, h]) {
    if (L >= 0.75) return [L, C, h];
    return [clamp(0.97 - 0.5 * L, 0.62, 0.93), Math.min(C, 0.14), h];
  },
  border([L, C, h]) {
    if (L >= 0.7) return [0.3 + (1 - L) * 0.5, C * 0.8, h];
    if (C > 0.04) return [Math.max(L, 0.62), C, h];
    return [0.55, C, h];
  },
  // Shadows stay dark; only light highlights (inset white lines) are dimmed.
  shadow([L, C, h]) {
    return L >= 0.7 ? [0.3 + (1 - L) * 0.5, C * 0.8, h] : [L, C, h];
  },
};

const NAMED = { white: [255, 255, 255], black: [0, 0, 0] };
function parseHex(hex) {
  let h = hex.slice(1);
  if (h.length === 3 || h.length === 4) h = [...h].map((c) => c + c).join("");
  const rgb = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
  const alpha = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
  return { rgb, alpha };
}
const COLOR = /#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3,4}\b|rgba?\(\s*\d+[\s,]+\d+[\s,]+\d+\s*(?:[,/]\s*[\d.]+%?\s*)?\)|\b(?:white|black)\b/g;
function mapColor(literal, role) {
  let rgb, alpha = 1;
  if (literal.startsWith("#")) ({ rgb, alpha } = parseHex(literal));
  else if (literal.startsWith("rgb")) {
    const n = literal.match(/[\d.]+%?/g);
    rgb = n.slice(0, 3).map(Number);
    if (n[3]) alpha = n[3].endsWith("%") ? parseFloat(n[3]) / 100 : Number(n[3]);
  } else rgb = NAMED[literal.toLowerCase()];
  return toHex(roles[role](rgbToOklch(rgb)), alpha);
}
const mapValue = (value, role) => value.replace(COLOR, (m) => mapColor(m, role));

function roleForProperty(prop) {
  if (prop.startsWith("--")) {
    if (/ink|text|muted|accent|link/.test(prop)) return "text";
    if (/line|border|edge|rule/.test(prop)) return "border";
    if (/canvas|surface|bg|fill|tile|soft|column|paper|sheet|ground|body/.test(prop)) return "bg";
    return null;
  }
  if (/^(background|background-color|background-image)$/.test(prop)) return "bg";
  if (/^(color|fill|caret-color|text-decoration-color|accent-color|-webkit-text-fill-color)$/.test(prop)) return "text";
  if (/^(box-shadow|text-shadow|filter|drop-shadow)$/.test(prop)) return "shadow";
  if (/^(border|border-[a-z-]*color|border-(top|right|bottom|left|block|inline)(-start|-end)?|outline|outline-color|column-rule|stroke)$/.test(prop)) return "border";
  return null;
}

// ---------- stylesheets ----------
function walkFiles(dir, test, out = []) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (name === "node_modules" || name.startsWith(".")) continue;
    if (statSync(path).isDirectory()) walkFiles(path, test, out);
    else if (test(name)) out.push(path);
  }
  return out;
}

const isCurrentDesign = (sel) => /html:not\(\[data-design="v2"\]\)/.test(sel);
const isRedesignWrapper = (sel) => sel.trim() === WRAP || sel.trim() === 'html[data-design="v2"]';
function relSelector(selector) {
  // Selectors are emitted inside `:where(html[data-design="v2"]) { ... }`; anchor html-level ones with &.
  return selector.split(",").map((part) => {
    const p = part.trim();
    for (const prefix of [WRAP, 'html[data-design="v2"]']) if (p.startsWith(prefix)) return `&${p.slice(prefix.length)}`;
    if (p.startsWith(":root")) return `&${p.slice(5)}`;
    if (/^html\b/.test(p)) return `&${p.slice(4)}`;
    return p;
  }).join(", ");
}

function darkBlockFor(css, file) {
  const tree = postcss.parse(css, { from: file });
  const out = [];
  tree.walkDecls((decl) => {
    const role = roleForProperty(decl.prop);
    if (!role) return;
    // Every color declaration is copied in source order, mapped or verbatim, so a later override
    // (transparent, a token, inherit) still beats an earlier hardcoded color inside the dark block.
    COLOR.lastIndex = 0;
    const literal = COLOR.test(decl.value);
    const chain = [];
    for (let node = decl.parent; node && node.type !== "root"; node = node.parent) chain.unshift(node);
    if (chain.some((n) => n.type === "rule" && isCurrentDesign(n.selector))) return;
    if (chain.some((n) => n.type === "atrule" && (/print|forced-colors|prefers-color-scheme/.test(n.params) || /keyframes|theme|font-face|property|utility|custom-variant/.test(n.name)))) return;
    const path = chain
      .filter((n, i) => !(n.type === "rule" && i === 0 && isRedesignWrapper(n.selector)))
      .map((n, i) => (n.type === "rule" ? (i === 0 ? relSelector(n.selector) : n.selector) : `@${n.name} ${n.params}`));
    if (!path.length || path.every((p) => p.startsWith("@"))) path.push("&");
    out.push({ path, literal, decl: `${decl.prop}: ${literal ? mapValue(decl.value, role) : decl.value}${decl.important ? " !important" : ""};` });
  });
  if (!out.some((entry) => entry.literal)) return "";
  const lines = [START, `@media ${MEDIA} {`, `  ${WRAP} {`];
  let open = [];
  for (const { path, decl } of out) {
    let same = 0;
    while (same < open.length && same < path.length && open[same] === path[same]) same++;
    while (open.length > same) { open.pop(); lines.push(`${"  ".repeat(open.length + 2)}}`); }
    for (const seg of path.slice(same)) { lines.push(`${"  ".repeat(open.length + 2)}${seg} {`); open.push(seg); }
    lines.push(`${"  ".repeat(open.length + 2)}${decl}`);
  }
  while (open.length) { open.pop(); lines.push(`${"  ".repeat(open.length + 2)}}`); }
  lines.push("  }", "}", "");
  return lines.join("\n");
}

const stylesheets = [
  join(root, "app/globals.css"),
  join(root, "app/pipeline-surfaces.css"),
  ...walkFiles(join(root, "components"), (n) => n.endsWith(".module.css")),
  ...walkFiles(join(root, "app"), (n) => n.endsWith(".module.css")),
];
let stale = [];
for (const file of stylesheets) {
  const text = readFileSync(file, "utf8");
  const base = text.includes(START) ? text.slice(0, text.indexOf(START)).replace(/\n+$/, "\n") : text;
  const block = darkBlockFor(base, file);
  const next = block ? `${base}\n${block}` : base;
  if (next !== text) { stale.push(relative(root, file)); if (!check) writeFileSync(file, next); }
}

// ---------- component classes and SVG attributes ----------
const esc = (s) => s.replace(/[[\]#:/.%(),!]/g, (c) => `\\${c}`);
const VARIANTS = {
  hover: (s) => `${s}:hover`, focus: (s) => `${s}:focus`, "focus-visible": (s) => `${s}:focus-visible`,
  "focus-within": (s) => `${s}:focus-within`, active: (s) => `${s}:active`, disabled: (s) => `${s}:disabled`,
  placeholder: (s) => `${s}::placeholder`, checked: (s) => `${s}:checked`,
};
const SCREENS = { sm: "(min-width: 40rem)", md: "(min-width: 48rem)", lg: "(min-width: 64rem)", xl: "(min-width: 80rem)", "2xl": "(min-width: 96rem)", "max-sm": "(width < 40rem)", "max-md": "(width < 48rem)", "max-lg": "(width < 64rem)" };
const UTILITIES = {
  bg: ["bg", (v) => `background-color: ${v}`], text: ["text", (v) => `color: ${v}`],
  border: ["border", (v) => `border-color: ${v}`], "border-t": ["border", (v) => `border-top-color: ${v}`],
  "border-b": ["border", (v) => `border-bottom-color: ${v}`], "border-l": ["border", (v) => `border-left-color: ${v}`],
  "border-r": ["border", (v) => `border-right-color: ${v}`], "border-x": ["border", (v) => `border-inline-color: ${v}`],
  "border-y": ["border", (v) => `border-block-color: ${v}`], outline: ["border", (v) => `outline-color: ${v}`],
  ring: ["border", (v) => `--tw-ring-color: ${v}`], fill: ["text", (v) => `fill: ${v}`], stroke: ["text", (v) => `stroke: ${v}`],
  decoration: ["text", (v) => `text-decoration-color: ${v}`], accent: ["text", (v) => `accent-color: ${v}`], caret: ["text", (v) => `caret-color: ${v}`],
};
const CLASS = /(?<![\w-])((?:[a-z0-9-]+:)*)(bg|text|border(?:-[tblrxy])?|outline|ring|fill|stroke|decoration|accent|caret|divide)-(\[#[0-9a-fA-F]{3,8}\]|white|black)(?:\/(\d{1,3}))?(?![\w\[-])/g;
const sources = [...walkFiles(join(root, "components"), (n) => n.endsWith(".tsx")), ...walkFiles(join(root, "app"), (n) => n.endsWith(".tsx"))];
const classes = new Set(), fills = new Set();
for (const file of sources) {
  const text = readFileSync(file, "utf8");
  for (const m of text.matchAll(CLASS)) classes.add(m[0]);
  for (const m of text.matchAll(/\b(fill|stroke|stopColor|stop-color)="(#[0-9a-fA-F]{3,8})"/g)) fills.add(`${m[1] === "stopColor" ? "stop-color" : m[1]}|${m[2].toLowerCase()}`);
}
const rules = [];
let skipped = 0;
for (const cls of [...classes].sort()) {
  const m = new RegExp(CLASS.source).exec(cls);
  const variants = m[1] ? m[1].slice(0, -1).split(":") : [];
  const util = m[2], raw = m[3], opacity = m[4];
  const literal = raw.startsWith("[") ? raw.slice(1, -1) : raw;
  const [role, decl] = util === "divide" ? ["border", (v) => `border-color: ${v}`] : UTILITIES[util];
  let color = mapColor(literal, role);
  if (opacity) color = `color-mix(in srgb, ${color} ${Number(opacity)}%, transparent)`;
  if (variants.some((v) => !VARIANTS[v] && !SCREENS[v])) { skipped++; continue; }
  let selector = `.${esc(cls)}`;
  for (const v of variants) if (VARIANTS[v]) selector = VARIANTS[v](selector);
  if (util === "divide") selector = `${selector} > :not(:last-child)`;
  const media = variants.filter((v) => SCREENS[v]).map((v) => SCREENS[v]);
  const body = `${selector} { ${decl(color)}; }`;
  rules.push(media.length ? `@media ${media.join(" and ")} { ${body} }` : body);
}
for (const entry of [...fills].sort()) {
  const [attr, hex] = entry.split("|");
  const role = rgbToOklch(parseHex(hex).rgb)[0] >= 0.8 ? "bg" : "text";
  const prop = attr === "stop-color" ? "stop-color" : attr;
  rules.push(`svg [${attr === "stop-color" ? "stop-color" : attr}="${hex}" i] { ${prop}: ${mapColor(hex, role)}; }`);
}
const generated = `${START.replace("do not edit below this line", "do not edit")}
/* Component classes and SVG attributes that hardcode a light color. Tokens: app/design-dark.css.
   In the utilities layer, like the classes they answer, so stylesheet rules still win over them. */
@layer utilities {
  @media ${MEDIA} {
    ${WRAP} {
${rules.map((r) => `      ${r}`).join("\n")}
    }
  }
}
`;
const generatedPath = join(root, "app/design-dark.generated.css");
let current = "";
try { current = readFileSync(generatedPath, "utf8"); } catch {}
if (current !== generated) { stale.push("app/design-dark.generated.css"); if (!check) writeFileSync(generatedPath, generated); }

if (check) {
  if (stale.length) { console.error(`Dark mode is stale; run npm run design:dark\n  ${stale.join("\n  ")}`); process.exit(1); }
  console.log("Dark mode is current.");
} else {
  console.log(`Dark mode: ${rules.length} component rules (${skipped} variant classes skipped), ${stale.length} files written.`);
}
