import type { PipelineAssessmentRecord } from "@/lib/assessment/assessment-records";
import { createEmptyAssessmentToolData } from "@/lib/assessment/assessment-tool-schema";
import { defaultAssessmentSectionVersions } from "@/lib/assessment/assessment-sections";

export type TrainingAssessmentMode = "schedule" | "interview";

const trainingActor = {
  id: "pipeline-training-assessor",
  name: "Training Assessor",
};

export function buildTrainingAssessment(mode: TrainingAssessmentMode): PipelineAssessmentRecord {
  const now = new Date();
  const scheduledStart = new Date(now.getTime() + 24 * 60 * 60 * 1_000);
  scheduledStart.setMinutes(0, 0, 0);
  const startedAt = mode === "interview" ? now.toISOString() : null;
  const data = {
    ...createEmptyAssessmentToolData(),
    resident_number: "TRAINING-001",
    resident_name: "Taylor Rivera",
    date_of_birth: "1988-02-14",
    community: "San Pablo",
    assessment_date: now.toISOString().slice(0, 10),
    assessor: trainingActor.name,
    referral_received_date: now.toISOString().slice(0, 10),
    referrer_name: "Jordan Lee",
    referrer_contact: "Synthetic county program",
    current_location: "Training Stabilization Center",
    time_at_current_location: "Two weeks",
    referring_facility: "Training Stabilization Center",
    prior_setting_bucket: "Acute psychiatric setting",
    county: "Alameda County",
    prior_hospitalizations_count: 3,
    prior_5150_5250_holds: "One 5150 hold documented in the supplied discharge summary from 2025.",
    prior_placements: "Adult residential setting | approximately eight months | transitioned after repeated nighttime departures | facility discharge note.",
    primary_diagnosis: "Schizoaffective disorder",
    diagnosis_categories: ["schizoaffective"],
    current_symptoms: "During the practice interview, the client is calm and answers direct questions. The client reports anxiety most evenings during transitions, which delays sleep. Facility staff describe the same evening pattern.",
    cognition_orientation: "Alert and oriented to person, place, time, and situation.",
    dress_assistance_level: "independent",
    bathing_assistance_level: "some_assistance",
    overall_hygiene_rating: 4,
    language_barrier: "no",
    linear_conversation: "yes",
    peer_interaction_rating: 3,
    staff_interaction_rating: 4,
    participates_in_programming: "yes",
    programming_notes: "The client reports attending two structured groups most weeks; current facility attendance records were not supplied.",
    ambulatory: "yes",
    mobility: "The client walked independently during the practice interview; no device or transfer support was reported.",
    conservatorship_type: "non_conserved",
    forensic_involvement: "no",
    arrest_history: "no",
    pc290_registration: "no",
    arson_history: "no",
    diversion_client: "no",
    medication_adherence: "no",
    medication_refusals_30_days: 2,
    medications_at_intake: ["Synthetic medication A, dose pending verification", "Synthetic medication B, dose pending verification"],
    im_injections: "no",
    substance_abuse_history: "yes",
    active_substance_use: "no",
    substances: ["amphetamines"],
    last_substance_use_date: "2025-12-02",
    use_pattern: "sporadic",
    longest_sobriety_months: 10,
    substance_use_insight: "yes",
    substance_use_insight_details: "The client connects prior use with sleep loss and housing instability and identifies avoiding former contacts as helpful.",
    physical_altercations: "no",
    self_harm_history: "yes",
    last_self_harm_incident: "Per the supplied discharge summary, the most recent documented incident occurred in 2025; the exact date is not available.",
    current_self_harm_ideation: "no",
    assault_history: "no",
    elopement_history: "yes",
    auditory_hallucinations: "yes",
    auditory_hallucination_nature: "The client reports hearing indistinct voices during periods of severe insomnia and denies current command content.",
    auditory_hallucination_frequency: "less_than_monthly",
    visual_hallucinations: "no",
    olfactory_hallucinations: "no",
    tactile_hallucinations: "no",
    gustatory_hallucinations: "no",
    hallucination_coping_strategies: "The client reports using music, a brief walk, and contact with staff when symptoms increase.",
    hallucination_distress_impairment: "The client reports mild distress and delayed sleep during the most recent occurrence.",
    physical_health_concerns: "yes",
    physical_health_diagnoses: "Type 2 diabetes is listed in the synthetic discharge summary.",
    physical_health_measures: "Facility staff currently monitor blood glucose per the supplied care plan.",
    diabetic: "yes",
    diabetic_details: "Blood-glucose monitoring is documented; the current frequency requires confirmation from the facility.",
    special_diet: "yes",
    skin_integrity_issue: "no",
    uses_dentures: "no",
    uses_hearing_aids: "no",
    uses_glasses: "yes",
    uses_oxygen: "no",
    uses_hospital_bed: "no",
    uses_cpap: "no",
    catheter_care: "no",
    colostomy: "no",
    ileostomy: "no",
    incontinence_issues: "no",
    family_involvement: "A sibling participates in planning with the client's permission.",
    housing_history: "The client reports two residential placements in the last three years and one six-month period with family.",
    prior_living_situation: "Adult residential setting before the current stabilization placement.",
    friendships_social_connections: "The client identifies one sibling and a former peer-support contact as reliable supports.",
    preferred_facility_characteristics: "A smaller setting near public transportation with a predictable daily routine.",
    placement_preferences_concerns: "The client is concerned about changing prescribers and wants medication appointments explained before transition.",
    discharge_planning_goals: "Build a stable routine and transition to an appropriate residential setting.",
    assessment_notes: "Practice case only. Preserve medication and hospitalization questions as unresolved until the named source confirms them.",
    source_file: "Synthetic training packet",
    match_confidence: 1,
    extraction_date: now.toISOString(),
  };

  return {
    ...data,
    assessment_id: `pipeline-training-${mode}`,
    canonical_client_id: null,
    resident_key: null,
    version: 1,
    created_at: now.toISOString(),
    updated_at: now.toISOString(),
    field_provenance: {},
    unmapped_fields: [],
    referral_id: 0,
    assessor_id: trainingActor.id,
    status: "draft",
    completed_at: null,
    created_by: trainingActor,
    updated_by: trainingActor,
    audit_events: [],
    section_versions: defaultAssessmentSectionVersions(),
    scheduled_start_at: mode === "interview" ? scheduledStart.toISOString() : null,
    scheduled_duration_minutes: mode === "interview" ? 60 : null,
    scheduled_method: mode === "interview" ? "in_person" : null,
    scheduled_location: mode === "interview" ? "Training interview room" : null,
    schedule_status: mode === "interview" ? "scheduled" : "unscheduled",
    started_at: startedAt,
    signed_at: null,
    signed_by: null,
    signature_version: 0,
    addenda: [],
  };
}
