import type {
  OperatorActivity,
  OperatorActivityKind,
  OperatorModule,
  OperatorModuleDefinition,
  OperatorProductLocation,
  OperatorRole,
  OperatorTrainingTrack,
} from "@/lib/training/operator-training-types";

export const OPERATOR_TRAINING_VERSION = "2026.08.operator.3";
export const OPERATOR_TRAINING_REVIEWED_AT = "2026-08-27";

const allRoles = ["admin", "assessment_coordinator", "reviewer", "viewer"] as const;
const writeRoles = ["admin", "assessment_coordinator", "reviewer"] as const;
const intakeRoles = ["admin", "assessment_coordinator"] as const;
const assessmentRoles = ["admin", "reviewer"] as const;
const leadRoles = ["admin", "assessment_coordinator"] as const;

const home = location("Home", "/", "components/pipeline/PipelineWelcome.tsx");
const workspaces = location("Workspaces", "/?view=referrals", "components/pipeline/ReferralHome.tsx");
const newReferral = location("New referral", "/?view=referrals&screen=packet", "components/pipeline/ReferralPacketCanvas.tsx");
const calendar = location("Calendar", "/?screen=calendar", "components/pipeline/PipelineCalendar.tsx");
const operations = location("Operations", "/?screen=operations", "components/pipeline/OperationsDashboard.tsx");
const profiles = location("Clients", "/?screen=profiles", "components/pipeline/ClientProfileDirectory.tsx");
const assessments = location("Assessments", "/assessments", "components/pipeline/AssessmentWorkspace.tsx");

export const operatorTrainingTracks: readonly OperatorTrainingTrack[] = [
  track("orientation", 1, "Safe foundations", "Foundations", "Understand Pipeline, your role, and the rules that protect a governed clinical workflow.", "Navigate confidently without exposing PHI or changing records outside your authority."),
  track("intake", 2, "Referral intake", "Intake", "Turn an inbound county referral into one complete, owned workspace.", "Create accurate referrals without duplicates or missing ownership."),
  track("documents", 3, "Packets and extraction", "Packets", "Upload, classify, verify, and approve source-backed packet information.", "Use automation as a draft while keeping the source document authoritative."),
  track("pre-assessment", 4, "Pre-assessment readiness", "Readiness", "Prepare identity, medications, requirements, assignment, and scheduling.", "Send assessors a ready, coherent record rather than a pile of files."),
  track("assessment", 5, "Assessment execution", "Assessment", "Schedule, conduct, document, complete, and sign the assessment safely.", "Produce a reviewable assessment with a defensible record of who did what."),
  track("decision", 6, "Recommendation to EHR", "Decision", "Separate recommendation, authorization, acceptance, and EHR handoff.", "Move accepted referrals forward without bypassing clinical or operational controls."),
  track("coordination", 7, "Team coordination", "Coordination", "Use queues, calendar, ownership, activity, and profiles to coordinate work.", "Keep work visible without duplicating records or relying on side channels."),
  track("operations", 8, "Operational oversight", "Operations", "Interpret dashboards, filters, reports, census, and exceptions correctly.", "Answer operational questions from governed data without overstating what it proves."),
  track("recovery", 9, "Exceptions and recovery", "Recovery", "Recover drafts, conflicts, failed processing, duplicates, and deleted work safely.", "Recognize stop conditions and recover without overwriting another user or losing evidence."),
  track("certification", 10, "Role certification", "Certification", "Demonstrate the complete workflow for your assigned role.", "Earn a traceable readiness result based on practice, scenarios, and teach-back."),
];

const moduleDefinitions: readonly OperatorModuleDefinition[] = [
  moduleDefinition({ id: "pipeline-purpose", trackId: "orientation", number: 1, title: "What Pipeline governs", summary: "Follow one governed record from inbound referral through packet, assessment, decision, and EHR handoff.", minutes: 45, audiences: allRoles, objectives: ["Explain the end-to-end workflow", "Distinguish a referral workspace from a client profile"], criticalActions: ["Use the existing workspace as the system of coordination", "Check stage and ownership before acting"], neverDo: ["Create a second record because the first is hard to find", "Treat a dashboard total as a clinical conclusion"], locations: [home, workspaces], practice: practice("Trace the workflow", "Use a synthetic referral and describe where packet, assessment, decision, and EHR status live.", ["Open Workspaces", "Open a synthetic referral", "Locate stage, owner, packet, assessment, and activity"], "Describe the governed record from intake to final handoff and identify its source of truth.", ["Names every major stage", "Distinguishes workspace and profile", "Uses no PHI"]), check: check("What is the primary purpose of a referral workspace?", ["Store one governed operational record through the admissions flow", "Replace the EHR", "Act as a shared file folder"], 0, "Pipeline coordinates the admissions workflow; it does not replace the EHR or reduce the record to files.") }),
  moduleDefinition({ id: "navigation-model", trackId: "orientation", number: 2, title: "Navigate without losing context", summary: "Use Home, Workspaces, Calendar, Clients, search, and Operations for their intended questions.", minutes: 40, audiences: allRoles, prerequisites: ["pipeline-purpose"], objectives: ["Choose the correct surface for a task", "Return to a referral without recreating it"], criticalActions: ["Use search and filters before creating anything", "Read the page title and active context"], neverDo: ["Use browser history as the only way to find work", "Assume similarly named clients are the same person"], locations: [home, workspaces, calendar, profiles, operations], practice: practice("Navigation relay", "Answer five synthetic questions using the correct destination.", ["Find active work", "Find a scheduled assessment", "Find a client profile", "Find a queue exception", "Return home"], "Record which surface answers each question and why.", ["Uses all five surfaces", "Explains the boundary of each", "Does not create data"]), check: check("Where should you look for a referral that needs action from you?", ["Your operational queue or Workspaces", "Client profile only", "A new referral form"], 0, "Queues and Workspaces expose active referral work; profiles summarize a client and a new form creates a different record.") }),
  moduleDefinition({ id: "roles-permissions", trackId: "orientation", number: 3, title: "Roles, ownership, and permissions", summary: "Understand coordinator, assessor/reviewer, administrator, and read-only boundaries.", minutes: 45, audiences: allRoles, prerequisites: ["pipeline-purpose"], objectives: ["Describe your permitted actions", "Escalate work that requires a different role"], criticalActions: ["Act only within assigned authority", "Use the recorded owner and decision actor"], neverDo: ["Share credentials", "Ask another user to sign or decide under your account"], locations: [operations, workspaces], practice: practice("Permission boundary drill", "Classify synthetic actions by the role that may perform them.", ["Classify intake creation", "Classify assessment signing", "Classify final decision", "Classify read-only reporting"], "Explain two actions you can perform and two that require escalation.", ["Names the correct role", "Preserves accountability", "Avoids credential sharing"]), check: check("An assessor completes an assessment but cannot record the final decision. What should happen?", ["Escalate through the workflow to an authorized decision role", "Use an administrator's login", "Change the stage directly"], 0, "The workflow deliberately separates clinical recommendation from authorized final decision.") }),
  moduleDefinition({ id: "phi-safe-use", trackId: "orientation", number: 4, title: "PHI-safe daily operation", summary: "Protect client information in screens, downloads, notes, training evidence, and support requests.", minutes: 55, audiences: allRoles, prerequisites: ["roles-permissions"], objectives: ["Recognize PHI exposure paths", "Use synthetic data in training and support"], criticalActions: ["Verify the intended record before viewing or editing", "Close or lock the application when unattended"], neverDo: ["Paste packet content into training evidence", "Send screenshots with PHI through unapproved channels"], locations: [workspaces, profiles], practice: practice("Safe support request", "Rewrite an unsafe support message into a PHI-free diagnostic report.", ["Remove names and DOB", "Keep route, timestamp, request ID, and behavior", "Describe impact without packet text"], "Write a synthetic PHI-free issue report that still gives engineering enough diagnostic context.", ["Contains no client data", "Includes reproducible steps", "Includes operational impact"]), check: check("What belongs in Learning Center evidence?", ["Synthetic examples and your own workflow explanation", "A real client screenshot", "Copied packet text with the name removed"], 0, "Training evidence must remain synthetic; de-identifying one field does not make copied clinical content safe.") }),

  moduleDefinition({ id: "inbound-triage", trackId: "intake", number: 5, title: "Triage an inbound referral", summary: "Determine whether an inbound item is new work, an update, or a duplicate before creating a workspace.", minutes: 50, audiences: intakeRoles, prerequisites: ["navigation-model", "phi-safe-use"], objectives: ["Classify inbound work", "Search before creating"], criticalActions: ["Search name, DOB, source, and timing", "Preserve the inbound source context"], neverDo: ["Create first and deduplicate later", "Discard an ambiguous update"], locations: [workspaces, newReferral], practice: practice("Triage three messages", "Classify synthetic inbound messages as new, update, or possible duplicate.", ["Search existing workspaces", "Compare stable identifiers", "Record the rationale"], "Explain the classification and next action for each synthetic message.", ["Searches first", "Flags uncertainty", "Preserves source context"]), check: check("You find a similar name but a different DOB. What is the safe action?", ["Treat it as unresolved and verify identity before linking", "Merge it immediately", "Ignore the DOB"], 0, "Identity ambiguity is a stop condition, not permission to merge on name.") }),
  moduleDefinition({ id: "create-referral", trackId: "intake", number: 6, title: "Create the referral shell", summary: "Create the minimum accurate workspace, then add packet-backed information without guessing.", minutes: 60, audiences: intakeRoles, prerequisites: ["inbound-triage"], objectives: ["Create one valid workspace", "Separate known, unknown, and pending fields"], criticalActions: ["Enter received date, community, source, and ownership accurately", "Leave unknown clinical fields unknown"], neverDo: ["Invent values to satisfy a form", "Put multiple people in one workspace"], locations: [newReferral], practice: practice("Create a synthetic referral", "Use only the supplied synthetic intake facts.", ["Start New referral", "Enter identity and source", "Assign the correct owner", "Save the workspace"], "List the fields you entered, the fields you intentionally left unknown, and why.", ["Creates one record", "Does not infer missing values", "Records source and ownership"]), check: check("A required-looking clinical field is absent from the email. What should you enter?", ["Leave it unknown and obtain source evidence", "Enter the most likely value", "Copy a value from a similar referral"], 0, "Unknown is safer than fabricated certainty.") }),
  moduleDefinition({ id: "demographics-source", trackId: "intake", number: 7, title: "Demographics and referral source", summary: "Capture identity, county, community, payer, contact, and referral source with clear provenance.", minutes: 50, audiences: intakeRoles, prerequisites: ["create-referral"], objectives: ["Record demographics consistently", "Preserve referral-source meaning"], criticalActions: ["Use source-backed spelling and dates", "Keep county, community, and referring organization distinct"], neverDo: ["Normalize ambiguous identity without review", "Use free text when a governed option exists"], locations: [newReferral], practice: practice("Normalize synthetic demographics", "Resolve formatting without changing meaning.", ["Compare email and face sheet", "Record disagreements", "Select governed community and source"], "Describe one safe normalization and one disagreement that must remain flagged.", ["Preserves original meaning", "Does not hide disagreement", "Uses governed values"]), check: check("The email and face sheet disagree on DOB. What should the record show?", ["A flagged conflict requiring verification", "Whichever source was opened first", "An averaged date"], 0, "Conflicting identity values require explicit human verification.") }),
  moduleDefinition({ id: "medication-intake", trackId: "intake", number: 8, title: "Medication context at intake", summary: "Capture current medication information as supplied so it can seed, not decide, the assessment medication section.", minutes: 55, audiences: intakeRoles, prerequisites: ["create-referral"], objectives: ["Record medication source and status", "Explain the handoff into assessment"], criticalActions: ["Preserve dose, route, frequency, and source when present", "Mark uncertainty and missing signatures"], neverDo: ["Reconcile medications clinically", "Convert an unverified list into an approved list"], locations: [newReferral, assessments], practice: practice("Medication handoff", "Enter a synthetic medication list and trace how it appears at assessment intake.", ["Record supplied medication text", "Mark source and document status", "Open assessment medication intake"], "Explain what carried forward and what still requires assessor verification.", ["Preserves supplied details", "Distinguishes carry-forward from verification", "Avoids clinical interpretation"]), check: check("What does a medication list carried into assessment mean?", ["It is intake context that the assessor must verify", "It is automatically clinically approved", "It replaces the signed medication document"], 0, "Carry-forward reduces re-entry; it does not convert source text into verified clinical truth.") }),

  moduleDefinition({ id: "upload-packet", trackId: "documents", number: 9, title: "Upload and classify a packet", summary: "Attach the right files to the right referral using the intended packet category.", minutes: 55, audiences: writeRoles, prerequisites: ["pipeline-purpose", "phi-safe-use"], objectives: ["Upload safely", "Recognize supported files and packet categories"], criticalActions: ["Verify the referral before upload", "Wait for the upload completion state"], neverDo: ["Upload the same packet to multiple referrals", "Assume filename proves document identity"], locations: [newReferral], practice: practice("Packet upload", "Attach a synthetic PDF and verify the visible completion state.", ["Open the correct workspace", "Select packet category", "Upload the synthetic file", "Confirm it appears on the workspace"], "Record the visible evidence that the correct file reached the correct referral.", ["Verifies workspace identity", "Confirms completion", "Uses a synthetic document"]), check: check("What proves an upload belongs to the intended referral?", ["The verified workspace and completed attachment state", "The filename alone", "The order of browser tabs"], 0, "The workspace association and completion state are authoritative; filenames can collide.") }),
  moduleDefinition({ id: "extraction-status", trackId: "documents", number: 10, title: "Understand extraction status", summary: "Read queued, processing, review-ready, failed, and retry states without promising instant extraction.", minutes: 45, audiences: writeRoles, prerequisites: ["upload-packet"], objectives: ["Interpret processing states", "Know when to wait, retry, or escalate"], criticalActions: ["Allow asynchronous processing to finish", "Use the recorded failure state and request ID"], neverDo: ["Upload duplicates because processing is not instant", "Repeatedly retry a permanent validation failure"], locations: [newReferral, operations], practice: practice("Status interpretation", "Classify synthetic extraction states and choose the next action.", ["Read packet status", "Distinguish active work from failure", "Choose wait, retry, or escalation"], "Explain the correct response to queued, review-ready, and failed states.", ["Understands async behavior", "Avoids duplicate uploads", "Escalates with useful diagnostics"]), check: check("A packet is queued and has no error. What is the normal action?", ["Wait for asynchronous processing and monitor status", "Upload it again", "Mark every field reviewed"], 0, "Queued is an active processing state, not evidence of failure.") }),
  moduleDefinition({ id: "review-extraction", trackId: "documents", number: 11, title: "Review extracted fields", summary: "Compare every important candidate with its source page, confidence, and alternatives before approval.", minutes: 70, audiences: writeRoles, prerequisites: ["extraction-status"], objectives: ["Approve source-backed values", "Correct or reject unsupported candidates"], criticalActions: ["Open field evidence", "Review identity, medication, and decision-critical fields carefully"], neverDo: ["Approve all because the packet looks clean", "Treat model confidence as truth"], locations: [newReferral], practice: practice("Field review", "Review synthetic extraction candidates with one planted conflict.", ["Open candidate evidence", "Compare image and value", "Approve supported values", "Correct or reject the conflict"], "Document which field required human correction and what source evidence controlled.", ["Finds the planted conflict", "Uses page evidence", "Does not rubber-stamp"]), check: check("A high-confidence value disagrees with the source image. Which wins?", ["The source image and human review", "The confidence score", "The first extracted value"], 0, "Confidence routes attention; it never overrides source evidence.") }),
  moduleDefinition({ id: "packet-completeness", trackId: "documents", number: 12, title: "Confirm packet completeness", summary: "Distinguish files received, required documents present, field review complete, and admission approval.", minutes: 55, audiences: writeRoles, prerequisites: ["review-extraction"], objectives: ["Assess completeness accurately", "Identify missing requirements"], criticalActions: ["Use the requirement checklist", "Record missing documents as work items"], neverDo: ["Equate upload success with packet completeness", "Mark approval before authorized review"], locations: [newReferral, operations], practice: practice("Completeness decision", "Evaluate a synthetic packet with one missing and one unsigned requirement.", ["Review requirement statuses", "Create the missing-information action", "Keep approval pending"], "State why the packet is not ready and the exact next action.", ["Finds both gaps", "Separates receipt from approval", "Creates a clear next action"]), check: check("All PDFs uploaded successfully. Is the packet complete?", ["Only if required documents and reviews are also complete", "Yes, upload success is enough", "Yes, if extraction confidence is high"], 0, "Transport success does not establish document completeness or human approval.") }),

  moduleDefinition({ id: "preassessment-checklist", trackId: "pre-assessment", number: 13, title: "Run the readiness checklist", summary: "Resolve packet, identity, contact, medication, ownership, and missing-information prerequisites before assessment.", minutes: 55, audiences: writeRoles, prerequisites: ["packet-completeness"], objectives: ["Recognize ready versus blocked", "Name the owner of every gap"], criticalActions: ["Use recorded work items", "Set an explicit next action and owner"], neverDo: ["Schedule around an unresolved identity conflict", "Keep blockers only in personal notes"], locations: [workspaces, operations], practice: practice("Ready or blocked", "Evaluate four synthetic referrals and classify readiness.", ["Check packet review", "Check identity and contact", "Check owner and open work", "Record the next action"], "Explain why each case is ready or blocked and who owns the next step.", ["Uses objective criteria", "Names ownership", "Does not hide blockers"]), check: check("A referral has a complete packet but no assigned assessor. Is it ready?", ["No; assignment is an explicit readiness dependency", "Yes; anyone can assess it", "Yes; calendar assignment happens automatically"], 0, "A complete packet without accountable ownership is not operationally ready.") }),
  moduleDefinition({ id: "assign-assessor", trackId: "pre-assessment", number: 14, title: "Assign the assessor", summary: "Assign assessment work deliberately and understand how ownership controls queues and access.", minutes: 40, audiences: leadRoles, prerequisites: ["preassessment-checklist"], objectives: ["Assign the correct assessor", "Recognize ownership-driven visibility"], criticalActions: ["Confirm assignee identity", "Reassign with a clear operational reason"], neverDo: ["Assign to a placeholder account", "Assume all assessors can see all cases"], locations: [workspaces, operations], practice: practice("Assignment drill", "Assign and reassign a synthetic referral while tracking the resulting queue owner.", ["Choose the initial assessor", "Verify My Queue visibility", "Reassign with reason", "Verify ownership changed"], "Describe the visible ownership changes and what should happen to accountability history.", ["Uses a real team identity", "Verifies queue impact", "Preserves history"]), check: check("Why can another assessor be unable to open the referral?", ["Referral access follows assignment and role boundaries", "The browser is broken", "All assessors should share one login"], 0, "Assignment is an access and accountability boundary, not only a label.") }),
  moduleDefinition({ id: "schedule-assessment", trackId: "pre-assessment", number: 15, title: "Schedule an assessment", summary: "Create a calendar-linked assessment with date, owner, method, and valid Zoom information when remote.", minutes: 50, audiences: writeRoles, prerequisites: ["preassessment-checklist"], objectives: ["Create a complete schedule", "Choose the correct meeting method"], criticalActions: ["Confirm time zone and participants", "Use Zoom for remote assessment when selected"], neverDo: ["Paste meeting credentials into unrestricted notes", "Create a calendar event without the referral association"], locations: [calendar, assessments], practice: practice("Schedule a Zoom assessment", "Use a synthetic referral and a non-live Zoom example.", ["Open assessment schedule", "Select date and time", "Choose Zoom", "Verify calendar linkage"], "Record the fields that make the schedule actionable and safely associated.", ["Includes owner and time", "Uses Zoom method", "Verifies calendar linkage"]), check: check("What makes a calendar event operationally useful?", ["It is linked to the referral and has owner, time, and method", "It contains the client name only", "It appears on any personal calendar"], 0, "The event must connect back to governed work and identify who, when, and how.") }),
  moduleDefinition({ id: "assessment-handoff", trackId: "pre-assessment", number: 16, title: "Hand off to the assessor", summary: "Give the assessor a concise, source-backed readiness summary without replacing the packet or assessment.", minutes: 45, audiences: writeRoles, prerequisites: ["assign-assessor", "schedule-assessment"], objectives: ["Create an actionable handoff", "Preserve unresolved questions"], criticalActions: ["State what is verified and what is pending", "Point to source documents and medication context"], neverDo: ["Resolve clinical ambiguity for the assessor", "Send a side-channel summary that is absent from Pipeline"], locations: [workspaces, assessments], practice: practice("Assessor handoff", "Prepare a synthetic readiness note for a scheduled case.", ["Summarize verified intake", "List unresolved questions", "Reference packet and medication source", "Confirm assessor ownership"], "Write a PHI-free handoff pattern that distinguishes verified facts from open questions.", ["Clear verified/pending boundary", "Points to sources", "Names next owner"]), check: check("What should a handoff do with an unresolved medication discrepancy?", ["Surface it explicitly for assessor verification", "Choose the newest-looking list", "Delete the older source"], 0, "Handoff makes uncertainty visible; it does not manufacture resolution.") }),

  moduleDefinition({ id: "assessment-start", trackId: "assessment", number: 17, title: "Start the assessment correctly", summary: "Verify the person, consent context, assignment, schedule, and record before changing assessment state.", minutes: 50, audiences: assessmentRoles, prerequisites: ["preassessment-checklist"], objectives: ["Perform a safe start", "Recognize when not to begin"], criticalActions: ["Confirm the assigned record", "Check readiness and schedule"], neverDo: ["Start an assessment for an ambiguous identity", "Document under another assessor"], locations: [assessments], practice: practice("Start gate", "Evaluate a synthetic scheduled assessment with one stop condition.", ["Confirm identity", "Confirm ownership", "Review readiness", "Identify the stop condition"], "Explain the start decision and the evidence that controls it.", ["Finds the stop condition", "Uses assigned record", "Does not bypass readiness"]), check: check("What should happen when identity cannot be confirmed at assessment start?", ["Stop and escalate for identity resolution", "Continue and fix it later", "Select the closest profile"], 0, "Identity ambiguity must be resolved before clinical documentation proceeds.") }),
  moduleDefinition({ id: "assessment-demographics", trackId: "assessment", number: 18, title: "Verify pre-assessment information", summary: "Confirm demographics, referral source, living context, medications, and other carried-forward information.", minutes: 65, audiences: assessmentRoles, prerequisites: ["assessment-start"], objectives: ["Verify carried-forward values", "Preserve corrections with provenance"], criticalActions: ["Compare carried values with interview and source", "Correct with an attributable note"], neverDo: ["Assume carried-forward means verified", "Erase the fact that a value changed"], locations: [assessments], practice: practice("Verify carried-forward data", "Review a synthetic assessment where intake and interview differ.", ["Inspect intake values", "Record assessor verification", "Correct one discrepancy", "Preserve source context"], "Describe the correction and why the assessment value differs from intake.", ["Verifies rather than copies", "Preserves provenance", "Explains discrepancy"]), check: check("A carried-forward field conflicts with the interview. What should the assessor do?", ["Record the verified assessment value and preserve the discrepancy context", "Keep the intake value silently", "Delete the source document"], 0, "Assessment verification can correct intake while retaining a defensible trail.") }),
  moduleDefinition({ id: "assessment-questionnaire", trackId: "assessment", number: 19, title: "Complete the assessment questionnaire", summary: "Document answers, observations, risks, and required narratives clearly and within the intended sections.", minutes: 85, audiences: assessmentRoles, prerequisites: ["assessment-demographics"], objectives: ["Complete required sections", "Write specific, supportable narratives"], criticalActions: ["Use direct observations and attributed statements", "Address required safety and functional domains"], neverDo: ["Copy-forward unsupported narratives", "Use stigmatizing or speculative language"], locations: [assessments], practice: practice("Structured assessment", "Complete a synthetic questionnaire from a supplied scenario.", ["Document responses", "Separate observation from report", "Complete safety fields", "Review missing sections"], "Explain how two narrative statements are supported and attributed.", ["Covers required domains", "Uses neutral language", "Separates observation and report"]), check: check("Which narrative is strongest?", ["A specific, attributed observation tied to the assessment context", "A vague conclusion with no source", "Copied text from an unrelated prior case"], 0, "Defensible documentation is specific, attributable, and relevant.") }),
  moduleDefinition({ id: "assessment-complete-sign", trackId: "assessment", number: 20, title: "Complete and sign", summary: "Resolve required fields, review the complete record, then sign so the assessment becomes an accountable clinical artifact.", minutes: 60, audiences: assessmentRoles, prerequisites: ["assessment-questionnaire"], objectives: ["Distinguish save, complete, and sign", "Verify readiness before signing"], criticalActions: ["Review validation errors", "Confirm the final record before signature"], neverDo: ["Sign an incomplete assessment", "Edit a signed record as if it were an unsigned draft"], locations: [assessments], practice: practice("Completion review", "Resolve synthetic validation gaps and perform a final sign-off review.", ["Run section review", "Resolve required gaps", "Complete the assessment", "Verify before signing"], "List the checks performed before signature and how later corrections should be handled.", ["Resolves required gaps", "Distinguishes completion and signature", "Mentions addendum/correction path"]), check: check("What does signing establish?", ["An accountable completed assessment by the signed-in assessor", "That every later change is unrestricted", "That the final admission decision is automatically accepted"], 0, "Signature establishes accountable assessment completion; decision authority remains separate.") }),

  moduleDefinition({ id: "recommendation", trackId: "decision", number: 21, title: "Submit the clinical recommendation", summary: "Translate the completed assessment into a clear recommendation with supporting rationale and limitations.", minutes: 55, audiences: assessmentRoles, prerequisites: ["assessment-complete-sign"], objectives: ["Submit a supportable recommendation", "Separate recommendation from final authority"], criticalActions: ["Reference completed assessment evidence", "State limitations or unresolved concerns"], neverDo: ["Record the final decision if not authorized", "Hide uncertainty to speed acceptance"], locations: [assessments, workspaces], practice: practice("Recommendation handoff", "Write a synthetic recommendation from a completed scenario.", ["Review signed assessment", "Choose recommendation", "Document rationale", "Identify final decision owner"], "Explain why the recommendation is supportable and who owns the next decision.", ["Uses assessment evidence", "States limitations", "Preserves role separation"]), check: check("Is a signed assessor recommendation the final admission decision?", ["No; an authorized role records the final decision", "Yes, automatically", "Only when the packet is large"], 0, "Recommendation and authorization are intentionally separate controls.") }),
  moduleDefinition({ id: "final-decision", trackId: "decision", number: 22, title: "Record the final decision", summary: "Review recommendation, requirements, and authority before recording accepted, declined, or deferred outcomes.", minutes: 60, audiences: leadRoles, prerequisites: ["preassessment-checklist"], objectives: ["Record a valid terminal decision", "Document rationale and actor"], criticalActions: ["Confirm authorization", "Use the explicit decision action and reason"], neverDo: ["Move stage to simulate a decision", "Overwrite a terminal decision because late data arrived"], locations: [workspaces, operations], practice: practice("Decision control", "Evaluate a synthetic recommendation with an unresolved requirement.", ["Review recommendation", "Review open requirements", "Choose decide or defer", "Record reason and actor"], "Explain the outcome and why a stage change alone would be insufficient.", ["Checks requirements", "Records actor and reason", "Uses decision control"]), check: check("How should late contradictory information affect a recorded terminal decision?", ["Use the governed review/reopen process; do not silently overwrite it", "Overwrite the decision", "Delete the late information"], 0, "Terminal decisions require an auditable change path.") }),
  moduleDefinition({ id: "move-in-requirements", trackId: "decision", number: 23, title: "Resolve move-in requirements", summary: "Complete admission documents and operational prerequisites before moving an accepted referral to admitted status.", minutes: 50, audiences: leadRoles, prerequisites: ["final-decision"], objectives: ["Identify blocking requirements", "Resolve or assign each blocker"], criticalActions: ["Use requirement status rather than memory", "Confirm accepted-only workflow"], neverDo: ["Mark admitted with open blocking requirements", "Treat decision acceptance as EHR completion"], locations: [workspaces, operations], practice: practice("Admission readiness", "Resolve synthetic missing agreement and medication-signature work items.", ["Open requirement list", "Assign missing items", "Confirm approvals", "Transition only when clear"], "List the requirements that block admission and the evidence that clears them.", ["Finds all blockers", "Uses recorded approval", "Transitions only after resolution"]), check: check("An accepted referral still has a missing signed agreement. What is the stage action?", ["Keep admission blocked until the requirement is resolved", "Mark admitted anyway", "Delete the requirement"], 0, "Acceptance does not bypass move-in requirements.") }),
  moduleDefinition({ id: "ehr-handoff", trackId: "decision", number: 24, title: "Complete the EHR handoff", summary: "Queue accepted records, monitor transfer state, recover failures, and confirm the downstream handoff.", minutes: 60, audiences: leadRoles, prerequisites: ["move-in-requirements"], objectives: ["Use accepted-only EHR export", "Recover failed handoffs safely"], criticalActions: ["Verify accepted/admitted status", "Record failure reason before retry"], neverDo: ["Export a pending or declined referral", "Assume queued means sent"], locations: [operations, workspaces], practice: practice("EHR failure recovery", "Process a synthetic accepted referral through queued, failed, retry, and sent states.", ["Queue handoff", "Read failure state", "Record reason", "Retry and verify sent"], "Explain each state and the evidence required before considering the handoff complete.", ["Uses accepted-only record", "Distinguishes queued and sent", "Preserves failure history"]), check: check("When is an EHR handoff complete?", ["When the system records the downstream sent/confirmed state", "When it is queued", "When the referral is created"], 0, "Queueing starts asynchronous work; it is not proof of downstream completion.") }),

  moduleDefinition({ id: "my-queue", trackId: "coordination", number: 25, title: "Work from My Queue", summary: "Prioritize assigned work by stage, blocker, urgency, and next action instead of relying on memory.", minutes: 45, audiences: writeRoles, prerequisites: ["navigation-model"], objectives: ["Interpret queue items", "Choose the next safe action"], criticalActions: ["Check owner and blocker", "Refresh after completing work"], neverDo: ["Work from an exported stale list", "Ignore items because they are old"], locations: [operations, workspaces], practice: practice("Queue prioritization", "Order a synthetic queue with urgent, blocked, and ready items.", ["Review stage", "Review blocker", "Review age and priority", "Choose the next three actions"], "Explain your priority order and which items require escalation instead of work.", ["Uses multiple signals", "Separates blocked from actionable", "Names escalation"]), check: check("Which item should generally be acted on first?", ["The highest-risk actionable item, considering urgency and blockers", "Always the newest item", "Any item with the shortest name"], 0, "Queues support judgment across urgency, age, readiness, and risk.") }),
  moduleDefinition({ id: "calendar-coordination", trackId: "coordination", number: 26, title: "Coordinate from Calendar", summary: "Use calendar views by day, week, month, community, and owner while keeping referral state authoritative.", minutes: 45, audiences: writeRoles, prerequisites: ["navigation-model"], objectives: ["Filter schedules correctly", "Open the underlying referral from an event"], criticalActions: ["Confirm the event is linked", "Update the assessment schedule rather than duplicating events"], neverDo: ["Create unrelated duplicate events", "Treat a calendar label as the full clinical record"], locations: [calendar], practice: practice("Calendar sweep", "Find synthetic assessments by week, community, and assessor.", ["Open month view", "Filter community", "Open an event", "Return to the referral"], "Explain which calendar question each view answers and where the authoritative state remains.", ["Uses filters correctly", "Opens linked referral", "Preserves one schedule"]), check: check("Where should a changed assessment time be updated?", ["On the linked assessment schedule so Calendar stays consistent", "In a separate unlinked event", "Only in a chat message"], 0, "The linked assessment schedule is the governed source for Calendar.") }),
  moduleDefinition({ id: "activity-collaboration", trackId: "coordination", number: 27, title: "Use activity and ownership history", summary: "Read who changed what, coordinate handoffs, and avoid overwriting concurrent work.", minutes: 50, audiences: writeRoles, prerequisites: ["my-queue"], objectives: ["Use activity as audit context", "Respond safely to concurrent edits"], criticalActions: ["Read current version after a conflict", "Reapply only your intended change"], neverDo: ["Blindly overwrite after a conflict", "Use activity as a substitute for required documentation"], locations: [workspaces, operations], practice: practice("Concurrent edit recovery", "Resolve a synthetic save conflict where another user updated assignment.", ["Read the conflict", "Reload current state", "Compare changes", "Reapply only the safe edit"], "Describe what changed remotely and why your final save does not erase it.", ["Preserves remote update", "Reapplies intended change", "Explains conflict"]), check: check("A save reports that the record changed in another session. What next?", ["Reload, compare, and reapply only the intended change", "Keep clicking save", "Overwrite the entire record"], 0, "Optimistic conflicts protect another user's work and require reconciliation.") }),

  moduleDefinition({ id: "dashboard-meaning", trackId: "operations", number: 28, title: "Read dashboards without overclaiming", summary: "Interpret census, referral, stage, timing, and exception metrics within their defined scope and freshness.", minutes: 55, audiences: allRoles, prerequisites: ["pipeline-purpose"], objectives: ["State metric scope and freshness", "Trace totals to underlying records"], criticalActions: ["Read filters and as-of context", "Open evidence rows for anomalies"], neverDo: ["Report a total without scope", "Treat operational status as clinical truth"], locations: [home, operations], practice: practice("Metric explanation", "Explain three synthetic metrics to a supervisor.", ["State time period", "State community and status scope", "Open underlying rows", "Name what the metric cannot prove"], "Write a concise metric explanation including scope, freshness, and limitation.", ["Names scope", "Names freshness", "Avoids clinical overclaim"]), check: check("What should accompany an operational total?", ["Scope, time period, freshness, and underlying evidence", "Only a screenshot", "A guess about why it changed"], 0, "A number without its contract is easy to misinterpret.") }),
  moduleDefinition({ id: "filter-report-export", trackId: "operations", number: 29, title: "Filter, report, and export", summary: "Use governed filters and accepted-only exports while checking that displayed and exported populations match.", minutes: 55, audiences: ["admin", "assessment_coordinator", "viewer"], prerequisites: ["dashboard-meaning"], objectives: ["Build a reproducible report", "Validate export population"], criticalActions: ["Record active filters", "Compare row count before export"], neverDo: ["Export broader PHI than necessary", "Rename filters after reporting results"], locations: [operations, workspaces], practice: practice("Reproducible report", "Build a synthetic monthly community report and verify its export count.", ["Set month", "Set community", "Review rows", "Compare export count"], "Record the exact filters, row count, and intended audience for the report.", ["Reproducible scope", "Counts reconcile", "Uses minimum necessary data"]), check: check("Before sharing an export, what must be verified?", ["The active scope, row count, audience, and minimum necessary fields", "Only the filename", "That it opens in Excel"], 0, "Export safety and correctness depend on scope and audience, not file format alone.") }),
  moduleDefinition({ id: "supervisor-exceptions", trackId: "operations", number: 30, title: "Run the supervisor exception queue", summary: "Use stale work, unowned records, failed processing, missing requirements, and EHR failures as actionable controls.", minutes: 60, audiences: leadRoles, prerequisites: ["dashboard-meaning", "my-queue"], objectives: ["Classify exception ownership", "Close the loop on escalations"], criticalActions: ["Assign an owner and next action", "Verify resolution removes the exception"], neverDo: ["Clear exceptions without resolving causes", "Use a spreadsheet as a parallel queue"], locations: [operations], practice: practice("Exception round", "Triage a synthetic supervisor queue containing four exception types.", ["Classify risk", "Assign owner", "Set next action", "Verify one resolution"], "Explain the priority, owner, and closure evidence for each exception.", ["Covers every item", "Names owner and action", "Verifies closure"]), check: check("When is an exception closed?", ["When the underlying condition is resolved and the queue reflects it", "When someone acknowledges it", "When it is copied to a spreadsheet"], 0, "Acknowledgment is not resolution; the source condition must clear.") }),

  moduleDefinition({ id: "draft-recovery", trackId: "recovery", number: 31, title: "Recover drafts and interrupted work", summary: "Recover browser or durable drafts after navigation, timeout, or restart without creating duplicate records.", minutes: 50, audiences: writeRoles, prerequisites: ["navigation-model"], objectives: ["Recognize recoverable state", "Reconcile a draft with the current record"], criticalActions: ["Compare draft and server versions", "Discard only after confirming saved state"], neverDo: ["Create a new referral to recover a draft", "Assume the draft is newer than the server"], locations: [newReferral, assessments], practice: practice("Interrupted-session recovery", "Recover a synthetic draft after a simulated reload.", ["Reopen the intended workspace", "Inspect recovery notice", "Compare current values", "Restore or discard deliberately"], "Describe the evidence used to choose restore or discard.", ["Avoids duplicate record", "Compares versions", "Makes a deliberate choice"]), check: check("What is the first response to a recovered draft?", ["Compare it with the current governed record", "Create another referral", "Discard it automatically"], 0, "Recovery must reconcile local work with server state.") }),
  moduleDefinition({ id: "duplicates-identity", trackId: "recovery", number: 32, title: "Handle duplicates and identity conflicts", summary: "Stop unsafe linking, preserve both records, and route possible matches through governed review.", minutes: 60, audiences: writeRoles, prerequisites: ["inbound-triage"], objectives: ["Recognize match versus collision", "Use confirmed linking only"], criticalActions: ["Compare stable identifiers and source evidence", "Escalate ambiguous collisions"], neverDo: ["Merge on name alone", "Delete one record to hide a conflict"], locations: [workspaces, profiles], practice: practice("Collision review", "Review synthetic records with same name, changed name, and same DOB collisions.", ["Compare stable identity", "Review source evidence", "Classify match or unresolved", "Record review rationale"], "Explain which pair can be linked and which must remain separate pending review.", ["Does not match on name alone", "Identifies collision", "Preserves both records"]), check: check("Two records share name and DOB but other stable evidence conflicts. What is safe?", ["Keep them unresolved and escalate identity review", "Merge them", "Delete the older record"], 0, "Even strong similarities can be collisions; contradictory stable evidence is a stop condition.") }),
  moduleDefinition({ id: "processing-failure", trackId: "recovery", number: 33, title: "Recover processing and handoff failures", summary: "Differentiate retryable, validation, permission, and downstream failures and preserve diagnostic evidence.", minutes: 60, audiences: leadRoles, prerequisites: ["extraction-status"], objectives: ["Choose retry versus escalation", "Provide useful PHI-free diagnostics"], criticalActions: ["Capture status, timestamp, and request ID", "Retry only when the failure class permits"], neverDo: ["Retry indefinitely", "Paste raw packet content into a support ticket"], locations: [operations, newReferral], practice: practice("Failure classification", "Classify four synthetic failures and choose an action.", ["Read status and reason", "Classify retryability", "Capture diagnostics", "Retry or escalate"], "Record the safe action and diagnostic fields for each failure.", ["Classifies correctly", "Avoids retry loops", "Keeps diagnostics PHI-free"]), check: check("A validation failure repeats after one corrected retry. What next?", ["Stop retrying and escalate with safe diagnostics", "Retry continuously", "Upload unrelated documents"], 0, "Repeated deterministic failures need investigation, not more pressure.") }),

  moduleDefinition({ id: "role-walkthrough", trackId: "certification", number: 34, title: "Role walkthrough", summary: "Perform your assigned role's complete workflow with synthetic data and explain every handoff.", minutes: 90, audiences: allRoles, prerequisites: ["phi-safe-use", "dashboard-meaning"], objectives: ["Complete the role path", "Explain upstream and downstream ownership"], criticalActions: ["Use synthetic records", "Narrate stop conditions"], neverDo: ["Use production PHI for certification", "Skip an action because the happy path works"], locations: [home, workspaces, calendar, operations], practice: practice("Full role rehearsal", "Run the synthetic workflow assigned to your role.", ["Start at the role's queue", "Complete each permitted action", "Hand off to the next role", "Verify the resulting state"], "Write a teach-back of your workflow, including two stop conditions and two handoffs.", ["Covers end-to-end role path", "Names boundaries", "Uses synthetic data"]), check: check("What makes a role walkthrough certifiable?", ["Observable actions, correct outcomes, and an explanation of controls", "Clicking every button", "Finishing as quickly as possible"], 0, "Certification measures safe operational competence, not navigation speed.") }),
  moduleDefinition({ id: "exception-drill", trackId: "certification", number: 35, title: "Exception drill", summary: "Demonstrate recovery from a conflict, identity ambiguity, missing requirement, or failed handoff.", minutes: 75, audiences: allRoles, prerequisites: ["role-walkthrough"], objectives: ["Recognize a stop condition", "Recover or escalate without data loss"], criticalActions: ["Protect existing evidence", "State who owns resolution"], neverDo: ["Force the happy path", "Hide an unresolved exception"], locations: [workspaces, operations], practice: practice("Exception capstone", "Complete one assigned synthetic exception drill.", ["Identify the control", "Stop unsafe progress", "Recover or escalate", "Verify final state"], "Explain the exception, the unsafe shortcut avoided, and the evidence of resolution.", ["Stops safely", "Preserves evidence", "Verifies resolution"]), check: check("What is the best response when the safe next action is unclear?", ["Stop, preserve state, and escalate to the accountable owner", "Guess and continue", "Delete the conflicting information"], 0, "A safe stop is an operational success when authority or evidence is unclear.") }),
  moduleDefinition({ id: "teach-back-certification", trackId: "certification", number: 36, title: "Teach-back and certification", summary: "Explain the workflow from memory, complete required scenarios, and identify where to find current job aids as Pipeline evolves.", minutes: 75, audiences: allRoles, prerequisites: ["role-walkthrough", "exception-drill"], objectives: ["Demonstrate durable understanding", "Know how training changes are communicated"], criticalActions: ["Use the current curriculum version", "Repeat changed modules after material product updates"], neverDo: ["Treat certification as permanent regardless of product change", "Rely on memorized screen positions alone"], locations: [home, workspaces, operations], practice: practice("Final teach-back", "Teach your workflow to a supervisor using a synthetic record.", ["Explain product purpose", "Demonstrate role actions", "Explain exception handling", "Locate current job aids"], "Record your complete role teach-back and one area that still requires supervised practice.", ["Accurate workflow", "Explains controls", "Names a development area"]), check: check("When Pipeline changes materially, what happens to training?", ["Affected modules are versioned, reviewed, and may require reassessment", "Nothing; certification never changes", "Users learn by trial and error"], 0, "Training is a maintained product control and must evolve with the application.") }),
];

export const operatorModules: readonly OperatorModule[] = moduleDefinitions.map((definition) => ({
  ...definition,
  activities: createActivities(definition),
}));

export const operatorModuleIds = operatorModules.map((module) => module.id);
export const operatorActivityIds = operatorModules.flatMap((module) => module.activities.map((activity) => operatorActivityKey(module.id, activity.id)));

export function operatorActivityKey(moduleId: string, activityId: string) {
  return `${moduleId}:${activityId}`;
}

export function getOperatorModule(moduleId: string) {
  return operatorModules.find((module) => module.id === moduleId);
}

export function getOperatorTrack(trackId: string) {
  return operatorTrainingTracks.find((track) => track.id === trackId);
}

export function operatorModulesForRole(role: OperatorRole) {
  const direct = new Set(operatorModules.filter((module) => module.audiences.includes(role)).map((module) => module.id));
  let changed = true;
  while (changed) {
    changed = false;
    for (const moduleId of [...direct]) {
      for (const prerequisite of getOperatorModule(moduleId)?.prerequisites ?? []) {
        if (!direct.has(prerequisite)) {
          direct.add(prerequisite);
          changed = true;
        }
      }
    }
  }
  return operatorModules.filter((module) => direct.has(module.id));
}

export function operatorMinutesForRole(role: OperatorRole) {
  return operatorModulesForRole(role).reduce((total, module) => total + module.minutes, 0);
}

export function primaryOperatorRole(roles: readonly string[]): OperatorRole {
  if (roles.includes("admin")) return "admin";
  if (roles.includes("assessment_coordinator")) return "assessment_coordinator";
  if (roles.includes("reviewer")) return "reviewer";
  return "viewer";
}

export function operatorRoleLabel(role: OperatorRole) {
  if (role === "admin") return "Operations administrator";
  if (role === "assessment_coordinator") return "Admissions coordinator";
  if (role === "reviewer") return "Assessor / reviewer";
  return "Read-only stakeholder";
}

function createActivities(module: OperatorModuleDefinition): readonly OperatorActivity[] {
  const briefingMinutes = Math.max(8, Math.round(module.minutes * 0.22));
  const walkthroughMinutes = Math.max(8, Math.round(module.minutes * 0.22));
  const scenarioMinutes = Math.max(12, Math.round(module.minutes * 0.41));
  const checkMinutes = Math.max(5, module.minutes - briefingMinutes - walkthroughMinutes - scenarioMinutes);
  return [
    activity(module, "briefing", "Understand the workflow", briefingMinutes, module.summary, [
      ...module.objectives.map((objective) => `Explain: ${objective}`),
      `Identify the boundary: ${module.neverDo[0]}`,
    ]),
    activity(module, "guided-practice", "Follow the safe path", walkthroughMinutes, `Walk through ${module.title.toLowerCase()} on the current Pipeline surface.`, [
      ...module.criticalActions.map((action) => `Locate and explain how to: ${action}`),
      "Use only synthetic information during training.",
    ]),
    activity(module, "scenario", module.practice.title, scenarioMinutes, module.practice.setup, module.practice.steps, {
      evidencePrompt: module.practice.evidencePrompt,
      acceptanceCriteria: module.practice.acceptanceCriteria,
    }),
    activity(module, "knowledge-check", "Verify your judgment", checkMinutes, "Choose the safest action and use the explanation to correct your mental model.", [
      "Answer without guessing from button position.",
      "Read the rationale before recording completion.",
    ], { check: module.check }),
  ];
}

function activity(
  module: OperatorModuleDefinition,
  kind: OperatorActivityKind,
  title: string,
  minutes: number,
  summary: string,
  instructions: readonly string[],
  optional: Partial<OperatorActivity> = {},
): OperatorActivity {
  return {
    id: kind,
    moduleId: module.id,
    kind,
    title,
    minutes,
    summary,
    instructions,
    locations: module.locations,
    ...optional,
  };
}

function moduleDefinition(input: Omit<OperatorModuleDefinition, "level" | "prerequisites"> & Partial<Pick<OperatorModuleDefinition, "level" | "prerequisites">>): OperatorModuleDefinition {
  return {
    level: input.number <= 12 ? "essential" : input.number <= 27 ? "role" : input.number <= 33 ? "advanced" : "lead",
    prerequisites: [],
    ...input,
  };
}

function practice(title: string, setup: string, steps: readonly string[], evidencePrompt: string, acceptanceCriteria: readonly string[]) {
  return { title, setup, steps, evidencePrompt, acceptanceCriteria };
}

function check(prompt: string, options: readonly [string, string, string], answer: 0 | 1 | 2, explanation: string) {
  return { prompt, options, answer, explanation };
}

function location(label: string, href: string, source: string): OperatorProductLocation {
  return { label, href, source };
}

function track(id: OperatorTrainingTrack["id"], number: number, title: string, shortTitle: string, summary: string, outcome: string): OperatorTrainingTrack {
  return { id, number, title, shortTitle, summary, outcome };
}
